'use client'
import { useState } from 'react'
import { Plus } from 'lucide-react'
import { useData } from '@/components/DataProvider'
import { TeacherPicker } from '@/components/TeacherPicker'
export default function Meetings(){
 const{data,loading,role,insert}=useData();const[meetingOpen,setMeetingOpen]=useState(false);const[actionOpen,setActionOpen]=useState(false);const leadership=['principal','vice_principal'].includes(role)
 const meetings=data.staff_meetings||[],actions=data.meeting_actions||[],teachers=data.teachers_dashboard||[]
 async function addMeeting(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await insert('staff_meetings',{title:f.get('title'),meeting_at:f.get('meeting_at'),location:f.get('location')||'',attendees:f.get('attendees')||'',minutes:f.get('minutes')||''});setMeetingOpen(false)}
 async function addAction(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await insert('meeting_actions',{meeting_id:Number(f.get('meeting_id')),teacher_id:f.get('teacher_id')?Number(f.get('teacher_id')):null,action:f.get('action'),due_date:f.get('due_date')||null,status:'Open'});setActionOpen(false)}
 if(loading)return <div className="loading">Loading meetings…</div>
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>Staff collaboration</span><h1 style={{marginTop:14}}>Meetings, minutes & actions</h1><p>Record staff briefings, attendees, minutes and accountable follow-up actions.</p></div>{leadership&&<div className="toolbar"><button className="btn" onClick={()=>setActionOpen(true)}><Plus size={15}/> Action item</button><button className="btn btn-primary" onClick={()=>setMeetingOpen(true)}><Plus size={15}/> Meeting</button></div>}</div>
 <div className="grid-2"><section className="panel"><div className="panel-head"><div><h2>Meeting records</h2><p>Staff briefings and minutes</p></div></div>{meetings.map((m:any)=><div className="queue-row" key={m.id}><div><b>{m.title}</b><small>{new Date(m.meeting_at).toLocaleString('en-GB',{timeZone:'Asia/Colombo'})} · {m.location||'School'}</small><small>Attendees: {m.attendees||'Not recorded'}</small><small>{m.minutes||'Minutes not added.'}</small></div></div>)}{!meetings.length&&<div className="empty">No meeting records.</div>}</section>
 <section className="panel"><div className="panel-head"><div><h2>Action tracker</h2><p>Responsibilities assigned from meetings</p></div></div>{actions.map((a:any)=><div className="queue-row" key={a.id}><div><b>{a.action}</b><small>{teachers.find((t:any)=>t.id===a.teacher_id)?.name||'Unassigned'} · due {a.due_date||'open'}</small></div><span className="status good">{a.status}</span></div>)}{!actions.length&&<div className="empty">No meeting actions.</div>}</section></div>
 {meetingOpen&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true"><div className="panel-head"><h2>New meeting</h2><button className="btn" onClick={()=>setMeetingOpen(false)}>Close</button></div><form className="form-grid" onSubmit={addMeeting}><div className="field"><label>TITLE</label><input name="title" required/></div><div className="field"><label>WHEN</label><input name="meeting_at" type="datetime-local" required/></div><div className="field"><label>LOCATION</label><input name="location"/></div><div className="field"><label>ATTENDEES</label><input name="attendees" placeholder="All staff / names"/></div><div className="field full"><label>MINUTES</label><textarea name="minutes" rows={6}/></div><button className="btn btn-primary full">Save meeting</button></form></div></div>}
 {actionOpen&&<div className="modal-backdrop"><div className="modal modal-form" role="dialog" aria-modal="true"><div className="panel-head"><h2>New action item</h2><button className="btn" onClick={()=>setActionOpen(false)}>Close</button></div><form className="form-grid" onSubmit={addAction}><div className="field"><label>MEETING</label><select name="meeting_id" required>{meetings.map((m:any)=><option key={m.id} value={m.id}>{m.title}</option>)}</select></div><div className="field"><label>ASSIGNEE</label><TeacherPicker name="teacher_id" required={false} allowEmpty={true} placeholder="Search teacher code, ID or name…"/></div><div className="field full"><label>ACTION</label><textarea name="action" rows={4} required/></div><div className="field"><label>DUE DATE</label><input name="due_date" type="date"/></div><button className="btn btn-primary full">Create action</button></form></div></div>}</>
}
