alter table public.training add column if not exists expiry_date date;
-- TeachTrack Advanced Competition Upgrade
-- Run after full-school-upgrade.sql.

create table if not exists public.departments(
 id bigint generated by default as identity primary key,
 name text not null unique,
 head_teacher_id bigint references public.teachers(id) on delete set null,
 description text not null default '',
 created_at timestamptz not null default now()
);
create table if not exists public.school_org_units(
 id bigint generated by default as identity primary key,
 name text not null,
 unit_type text not null check(unit_type in ('School','Section','Grade','Department')),
 parent_id bigint references public.school_org_units(id) on delete cascade,
 leader_teacher_id bigint references public.teachers(id) on delete set null,
 created_at timestamptz not null default now()
);
create table if not exists public.teacher_service_history(
 id bigint generated by default as identity primary key,
 teacher_id bigint not null references public.teachers(id) on delete cascade,
 event_type text not null check(event_type in ('Appointment','Promotion','Transfer','Service Grade','Responsibility','Other')),
 title text not null,
 institution text not null default '',
 effective_date date not null,
 notes text not null default '',
 created_at timestamptz not null default now()
);
create table if not exists public.duty_roster(
 id bigint generated by default as identity primary key,
 teacher_id bigint not null references public.teachers(id) on delete cascade,
 duty_date date not null,
 duty_type text not null,
 location text not null default '',
 start_time time,
 end_time time,
 status text not null default 'Assigned' check(status in ('Assigned','Completed','Cancelled')),
 notes text not null default '',
 created_at timestamptz not null default now()
);
create table if not exists public.staff_meetings(
 id bigint generated by default as identity primary key,
 title text not null,
 meeting_at timestamptz not null,
 location text not null default '',
 minutes text not null default '',
 created_by uuid default auth.uid() references auth.users(id) on delete set null,
 created_at timestamptz not null default now()
);
alter table public.staff_meetings add column if not exists attendees text not null default '';
create table if not exists public.meeting_actions(
 id bigint generated by default as identity primary key,
 meeting_id bigint references public.staff_meetings(id) on delete cascade,
 teacher_id bigint references public.teachers(id) on delete set null,
 action text not null,
 due_date date,
 status text not null default 'Open' check(status in ('Open','In Progress','Done')),
 created_at timestamptz not null default now()
);
create table if not exists public.qr_attendance_sessions(
 id bigint generated by default as identity primary key,
 session_date date not null default current_date,
 code text not null unique,
 opens_at timestamptz not null default now(),
 closes_at timestamptz not null,
 created_by uuid default auth.uid() references auth.users(id) on delete set null,
 active boolean not null default true,
 created_at timestamptz not null default now()
);
create table if not exists public.qr_attendance_checkins(
 id bigint generated by default as identity primary key,
 session_id bigint not null references public.qr_attendance_sessions(id) on delete cascade,
 teacher_id bigint not null references public.teachers(id) on delete cascade,
 checked_in_at timestamptz not null default now(),
 unique(session_id,teacher_id)
);
create table if not exists public.school_archives(
 id bigint generated by default as identity primary key,
 academic_year int not null unique,
 title text not null,
 closed_at timestamptz not null default now(),
 summary jsonb not null default '{}'::jsonb,
 created_by uuid default auth.uid() references auth.users(id) on delete set null
);

alter table public.departments enable row level security;
alter table public.school_org_units enable row level security;
alter table public.teacher_service_history enable row level security;
alter table public.duty_roster enable row level security;
alter table public.staff_meetings enable row level security;
alter table public.meeting_actions enable row level security;
alter table public.qr_attendance_sessions enable row level security;
alter table public.qr_attendance_checkins enable row level security;
alter table public.school_archives enable row level security;

do $$
declare t text;
begin
  foreach t in array array['departments','school_org_units','staff_meetings','meeting_actions','school_archives']
  loop
    execute format('drop policy if exists "%s read" on public.%I',t,t);
    execute format('create policy "%s read" on public.%I for select to authenticated using(true)',t,t);
    execute format('drop policy if exists "%s leadership write" on public.%I',t,t);
    execute format('create policy "%s leadership write" on public.%I for all to authenticated using(public.is_manager()) with check(public.is_manager())',t,t);
  end loop;
end $$;

drop policy if exists "service own or leadership read" on public.teacher_service_history;
create policy "service own or leadership read" on public.teacher_service_history for select to authenticated using(public.is_manager() or teacher_id=public.my_teacher_id());
drop policy if exists "service leadership write" on public.teacher_service_history;
create policy "service leadership write" on public.teacher_service_history for all to authenticated using(public.is_manager()) with check(public.is_manager());

drop policy if exists "duty own or leadership read" on public.duty_roster;
create policy "duty own or leadership read" on public.duty_roster for select to authenticated using(public.is_manager() or teacher_id=public.my_teacher_id());
drop policy if exists "duty leadership write" on public.duty_roster;
create policy "duty leadership write" on public.duty_roster for all to authenticated using(public.is_manager()) with check(public.is_manager());

drop policy if exists "qr sessions read" on public.qr_attendance_sessions;
create policy "qr sessions read" on public.qr_attendance_sessions for select to authenticated using(true);
drop policy if exists "qr sessions leadership write" on public.qr_attendance_sessions;
create policy "qr sessions leadership write" on public.qr_attendance_sessions for all to authenticated using(public.is_manager()) with check(public.is_manager());

drop policy if exists "qr checkins read" on public.qr_attendance_checkins;
create policy "qr checkins read" on public.qr_attendance_checkins for select to authenticated using(public.is_manager() or teacher_id=public.my_teacher_id());
drop policy if exists "qr checkins own insert" on public.qr_attendance_checkins;
create policy "qr checkins own insert" on public.qr_attendance_checkins for insert to authenticated with check(teacher_id=public.my_teacher_id() or public.is_manager());

grant select,insert,update,delete on public.departments,public.school_org_units,public.teacher_service_history,
public.duty_roster,public.staff_meetings,public.meeting_actions,public.qr_attendance_sessions,
public.qr_attendance_checkins,public.school_archives to authenticated;
grant usage,select on all sequences in schema public to authenticated;


alter table public.timetable_classes add column if not exists student_count int not null default 0;

create table if not exists public.subjects(
 id bigint generated by default as identity primary key,
 code text not null unique,
 name text not null,
 department_id bigint references public.departments(id) on delete set null,
 medium text not null default 'English' check(medium in ('Sinhala','Tamil','English')),
 active boolean not null default true,
 created_at timestamptz not null default now()
);
create table if not exists public.login_events(
 id bigint generated by default as identity primary key,
 user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
 signed_in_at timestamptz not null default now(),
 client_note text not null default 'Web sign-in'
);
alter table public.subjects enable row level security;
alter table public.login_events enable row level security;
drop policy if exists "subjects read" on public.subjects;
create policy "subjects read" on public.subjects for select to authenticated using(true);
drop policy if exists "subjects leadership write" on public.subjects;
create policy "subjects leadership write" on public.subjects for all to authenticated using(public.is_manager()) with check(public.is_manager());
drop policy if exists "login own or leadership read" on public.login_events;
create policy "login own or leadership read" on public.login_events for select to authenticated using(user_id=auth.uid() or public.is_manager());
drop policy if exists "login self insert" on public.login_events;
create policy "login self insert" on public.login_events for insert to authenticated with check(user_id=auth.uid());
grant select,insert,update,delete on public.subjects to authenticated;
grant select,insert on public.login_events to authenticated;
