-- TeachTrack advanced usability + professional development workflow upgrade
-- Run after the existing TeachTrack upgrade chain. Designed to be rerunnable.

create table if not exists public.goal_checkins (
  id bigint generated by default as identity primary key,
  goal_id bigint not null references public.goals(id) on delete cascade,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  progress int not null default 0 check(progress between 0 and 100),
  note text not null default '',
  evidence_url text,
  checkin_date date not null default current_date,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.evidence_attachments (
  id bigint generated by default as identity primary key,
  teacher_id bigint references public.teachers(id) on delete cascade,
  entity_type text not null,
  entity_id bigint,
  title text not null,
  storage_path text not null,
  storage_provider text not null default 'supabase' check(storage_provider in ('supabase','google_drive')),
  drive_file_id text,
  drive_name text,
  file_type text not null default '',
  notes text not null default '',
  uploaded_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_reads (
  id bigint generated by default as identity primary key,
  notification_id bigint not null references public.notifications(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  read_at timestamptz not null default now(),
  unique(notification_id,user_id)
);

create table if not exists public.notification_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade unique,
  training boolean not null default true,
  observations boolean not null default true,
  goals boolean not null default true,
  timetable boolean not null default true,
  achievements boolean not null default true,
  general boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.school_goals (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'School Improvement',
  description text not null default '',
  target_value numeric not null default 100,
  current_value numeric not null default 0,
  unit text not null default '%',
  due_date date,
  status text not null default 'Active' check(status in ('Active','On Track','At Risk','Completed')),
  owner_teacher_id bigint references public.teachers(id) on delete set null,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.mentoring_pairs (
  id bigint generated by default as identity primary key,
  mentor_teacher_id bigint not null references public.teachers(id) on delete cascade,
  mentee_teacher_id bigint not null references public.teachers(id) on delete cascade,
  focus_area text not null default '',
  start_date date not null default current_date,
  end_date date,
  status text not null default 'Active' check(status in ('Active','Completed','Paused')),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check(mentor_teacher_id <> mentee_teacher_id)
);

create table if not exists public.mentoring_sessions (
  id bigint generated by default as identity primary key,
  pair_id bigint not null references public.mentoring_pairs(id) on delete cascade,
  session_date date not null default current_date,
  objective text not null,
  notes text not null default '',
  next_step text not null default '',
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_skill_evidence (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  skill text not null,
  level int not null default 3 check(level between 1 and 5),
  evidence text not null default '',
  reviewed_by uuid default auth.uid() references auth.users(id) on delete set null,
  reviewed_at date not null default current_date,
  unique(teacher_id,skill)
);

create table if not exists public.observation_followups (
  id bigint generated by default as identity primary key,
  observation_id bigint not null references public.observations(id) on delete cascade,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  recommendation text not null,
  acknowledged boolean not null default false,
  linked_goal_id bigint references public.goals(id) on delete set null,
  followup_date date,
  outcome text not null default '',
  status text not null default 'Open' check(status in ('Open','Acknowledged','Goal Created','Reviewed','Closed')),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.saved_report_presets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  configuration jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(user_id,name)
);

-- RLS
alter table public.goal_checkins enable row level security;
alter table public.evidence_attachments enable row level security;
alter table public.notification_reads enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.school_goals enable row level security;
alter table public.mentoring_pairs enable row level security;
alter table public.mentoring_sessions enable row level security;
alter table public.teacher_skill_evidence enable row level security;
alter table public.observation_followups enable row level security;
alter table public.saved_report_presets enable row level security;

drop policy if exists goal_checkins_read on public.goal_checkins;
create policy goal_checkins_read on public.goal_checkins for select to authenticated using (
  public.can_review() or teacher_id=(select teacher_id from public.profiles where id=auth.uid())
);
drop policy if exists goal_checkins_write on public.goal_checkins;
create policy goal_checkins_write on public.goal_checkins for all to authenticated using (
  public.can_review() or teacher_id=(select teacher_id from public.profiles where id=auth.uid())
) with check (
  public.can_review() or teacher_id=(select teacher_id from public.profiles where id=auth.uid())
);

drop policy if exists evidence_read on public.evidence_attachments;
create policy evidence_read on public.evidence_attachments for select to authenticated using (
  public.can_review() or teacher_id=(select teacher_id from public.profiles where id=auth.uid())
);
drop policy if exists evidence_write on public.evidence_attachments;
create policy evidence_write on public.evidence_attachments for all to authenticated using (
  public.can_review() or teacher_id=(select teacher_id from public.profiles where id=auth.uid())
) with check (
  public.can_review() or teacher_id=(select teacher_id from public.profiles where id=auth.uid())
);

drop policy if exists notification_reads_own on public.notification_reads;
create policy notification_reads_own on public.notification_reads for all to authenticated
using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists notification_preferences_own on public.notification_preferences;
create policy notification_preferences_own on public.notification_preferences for all to authenticated
using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists school_goals_read on public.school_goals;
create policy school_goals_read on public.school_goals for select to authenticated using(true);
drop policy if exists school_goals_manage on public.school_goals;
create policy school_goals_manage on public.school_goals for all to authenticated
using(public.has_role(array['principal','vice_principal','section_head']))
with check(public.has_role(array['principal','vice_principal','section_head']));

drop policy if exists mentoring_pairs_read on public.mentoring_pairs;
create policy mentoring_pairs_read on public.mentoring_pairs for select to authenticated using (
  public.can_review() or mentor_teacher_id=(select teacher_id from public.profiles where id=auth.uid())
  or mentee_teacher_id=(select teacher_id from public.profiles where id=auth.uid())
);
drop policy if exists mentoring_pairs_manage on public.mentoring_pairs;
create policy mentoring_pairs_manage on public.mentoring_pairs for all to authenticated
using(public.can_review()) with check(public.can_review());

drop policy if exists mentoring_sessions_read on public.mentoring_sessions;
create policy mentoring_sessions_read on public.mentoring_sessions for select to authenticated using (
  public.can_review() or exists(
    select 1 from public.mentoring_pairs p
    where p.id=pair_id and (
      p.mentor_teacher_id=(select teacher_id from public.profiles where id=auth.uid())
      or p.mentee_teacher_id=(select teacher_id from public.profiles where id=auth.uid())
    )
  )
);
drop policy if exists mentoring_sessions_write on public.mentoring_sessions;
create policy mentoring_sessions_write on public.mentoring_sessions for all to authenticated using (
  public.can_review() or exists(
    select 1 from public.mentoring_pairs p
    where p.id=pair_id and p.mentor_teacher_id=(select teacher_id from public.profiles where id=auth.uid())
  )
) with check (
  public.can_review() or exists(
    select 1 from public.mentoring_pairs p
    where p.id=pair_id and p.mentor_teacher_id=(select teacher_id from public.profiles where id=auth.uid())
  )
);

drop policy if exists skill_evidence_read on public.teacher_skill_evidence;
create policy skill_evidence_read on public.teacher_skill_evidence for select to authenticated using (
  public.can_review() or teacher_id=(select teacher_id from public.profiles where id=auth.uid())
);
drop policy if exists skill_evidence_manage on public.teacher_skill_evidence;
create policy skill_evidence_manage on public.teacher_skill_evidence for all to authenticated
using(public.can_review()) with check(public.can_review());

drop policy if exists observation_followups_read on public.observation_followups;
create policy observation_followups_read on public.observation_followups for select to authenticated using (
  public.can_review() or teacher_id=(select teacher_id from public.profiles where id=auth.uid())
);
drop policy if exists observation_followups_write on public.observation_followups;
create policy observation_followups_write on public.observation_followups for all to authenticated using (
  public.can_review() or teacher_id=(select teacher_id from public.profiles where id=auth.uid())
) with check (
  public.can_review() or teacher_id=(select teacher_id from public.profiles where id=auth.uid())
);

drop policy if exists saved_report_presets_own on public.saved_report_presets;
create policy saved_report_presets_own on public.saved_report_presets for all to authenticated
using(user_id=auth.uid()) with check(user_id=auth.uid());

create index if not exists idx_goal_checkins_goal on public.goal_checkins(goal_id,checkin_date desc);
create index if not exists idx_evidence_entity on public.evidence_attachments(entity_type,entity_id);
create index if not exists idx_observation_followups_teacher on public.observation_followups(teacher_id,status);
create index if not exists idx_mentoring_pairs_teachers on public.mentoring_pairs(mentor_teacher_id,mentee_teacher_id);


alter table public.teacher_documents add column if not exists archived boolean not null default false;
alter table public.teacher_documents add column if not exists version int not null default 1;
