-- TeachTrack Complete Sri Lankan School Operations Upgrade
-- Run AFTER schema.sql, RBAC/user-control, and timetable-upgrade.sql.

create table if not exists public.academic_terms(
  id bigint generated by default as identity primary key,
  academic_year int not null,
  name text not null,
  start_date date not null,
  end_date date not null,
  status text not null default 'Upcoming' check(status in ('Upcoming','Active','Closed')),
  created_at timestamptz not null default now(),
  unique(academic_year,name)
);

create table if not exists public.leave_requests(
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  requested_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  leave_type text not null check(leave_type in ('Casual','Medical','Duty','Personal','Other')),
  start_date date not null,
  end_date date not null,
  reason text not null default '',
  status text not null default 'Pending' check(status in ('Pending','Approved','Rejected','Cancelled')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  check(end_date>=start_date)
);

create table if not exists public.school_events(
  id bigint generated by default as identity primary key,
  title text not null,
  event_type text not null default 'School Event',
  start_at timestamptz not null,
  end_at timestamptz,
  audience text not null default 'All Staff',
  location text not null default '',
  notes text not null default '',
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.exam_responsibilities(
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  exam_name text not null,
  responsibility text not null check(responsibility in ('Paper Setting','Moderation','Invigilation','Marking','Results','Other')),
  subject text not null default '',
  grade text not null default '',
  due_date date,
  status text not null default 'Assigned' check(status in ('Assigned','In Progress','Completed')),
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_documents(
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  title text not null,
  document_type text not null default 'Other',
  storage_path text not null,
  expiry_date date,
  uploaded_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.development_plans(
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  title text not null,
  focus_area text not null,
  action_steps text not null default '',
  target_date date,
  progress int not null default 0 check(progress between 0 and 100),
  status text not null default 'Active' check(status in ('Active','On Track','At Risk','Completed')),
  assigned_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.observation_rubrics(
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  max_score int not null default 5 check(max_score between 1 and 10),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.observation_scores(
  id bigint generated by default as identity primary key,
  observation_id bigint references public.observations(id) on delete cascade,
  rubric_id bigint not null references public.observation_rubrics(id) on delete cascade,
  score numeric(5,2) not null,
  note text not null default '',
  created_at timestamptz not null default now(),
  unique(observation_id,rubric_id)
);

create table if not exists public.notifications(
  id bigint generated by default as identity primary key,
  recipient_user_id uuid references auth.users(id) on delete cascade,
  title text not null,
  message text not null,
  category text not null default 'General',
  priority text not null default 'Normal' check(priority in ('Normal','High')),
  read_at timestamptz,
  action_url text,
  created_at timestamptz not null default now()
);

insert into public.observation_rubrics(name,description,max_score) values
('Lesson Preparation','Objectives, structure, materials and readiness',5),
('Subject Knowledge','Accuracy, depth and confident explanation',5),
('Classroom Management','Time, routines, behaviour and learning environment',5),
('Student Engagement','Participation, questioning and learner involvement',5),
('Assessment for Learning','Checks for understanding and useful feedback',5),
('Technology & Resources','Purposeful use of available teaching resources',5)
on conflict(name) do nothing;

insert into public.academic_terms(academic_year,name,start_date,end_date,status)
values
(extract(year from current_date)::int,'Term 1',make_date(extract(year from current_date)::int,1,1),make_date(extract(year from current_date)::int,4,30),'Active')
on conflict(academic_year,name) do nothing;

insert into storage.buckets(id,name,public)
values('teacher-documents','teacher-documents',false)
on conflict(id) do update set public=false;

alter table public.academic_terms enable row level security;
alter table public.leave_requests enable row level security;
alter table public.school_events enable row level security;
alter table public.exam_responsibilities enable row level security;
alter table public.teacher_documents enable row level security;
alter table public.development_plans enable row level security;
alter table public.observation_rubrics enable row level security;
alter table public.observation_scores enable row level security;
alter table public.notifications enable row level security;

-- Academic terms
drop policy if exists "terms read" on public.academic_terms;
create policy "terms read" on public.academic_terms for select to authenticated using(true);
drop policy if exists "terms leadership write" on public.academic_terms;
create policy "terms leadership write" on public.academic_terms for all to authenticated using(public.is_manager()) with check(public.is_manager());

-- Leave
drop policy if exists "leave own or leadership read" on public.leave_requests;
create policy "leave own or leadership read" on public.leave_requests for select to authenticated
using(public.is_manager() or teacher_id=public.my_teacher_id());
drop policy if exists "leave own create" on public.leave_requests;
create policy "leave own create" on public.leave_requests for insert to authenticated
with check(teacher_id=public.my_teacher_id() or public.is_manager());
drop policy if exists "leave leadership update" on public.leave_requests;
create policy "leave leadership update" on public.leave_requests for update to authenticated
using(public.is_manager() or (teacher_id=public.my_teacher_id() and status='Pending'))
with check(public.is_manager() or (teacher_id=public.my_teacher_id() and status='Pending'));

-- Calendar
drop policy if exists "events read" on public.school_events;
create policy "events read" on public.school_events for select to authenticated using(true);
drop policy if exists "events leadership write" on public.school_events;
create policy "events leadership write" on public.school_events for all to authenticated using(public.is_manager()) with check(public.is_manager());

-- Exam responsibilities
drop policy if exists "exam own or leadership read" on public.exam_responsibilities;
create policy "exam own or leadership read" on public.exam_responsibilities for select to authenticated
using(public.is_manager() or teacher_id=public.my_teacher_id());
drop policy if exists "exam leadership write" on public.exam_responsibilities;
create policy "exam leadership write" on public.exam_responsibilities for all to authenticated using(public.is_manager()) with check(public.is_manager());

-- Documents
drop policy if exists "documents own or leadership read" on public.teacher_documents;
create policy "documents own or leadership read" on public.teacher_documents for select to authenticated
using(public.is_manager() or teacher_id=public.my_teacher_id());
drop policy if exists "documents own or leadership write" on public.teacher_documents;
create policy "documents own or leadership write" on public.teacher_documents for all to authenticated
using(public.is_manager() or teacher_id=public.my_teacher_id())
with check(public.is_manager() or teacher_id=public.my_teacher_id());

-- Development plans
drop policy if exists "plans own or review read" on public.development_plans;
create policy "plans own or review read" on public.development_plans for select to authenticated
using(public.can_review() or teacher_id=public.my_teacher_id());
drop policy if exists "plans review write" on public.development_plans;
create policy "plans review write" on public.development_plans for all to authenticated
using(public.can_review()) with check(public.can_review());

-- Rubrics and scores
drop policy if exists "rubrics read" on public.observation_rubrics;
create policy "rubrics read" on public.observation_rubrics for select to authenticated using(true);
drop policy if exists "rubrics leadership write" on public.observation_rubrics;
create policy "rubrics leadership write" on public.observation_rubrics for all to authenticated using(public.is_manager()) with check(public.is_manager());
drop policy if exists "scores read" on public.observation_scores;
create policy "scores read" on public.observation_scores for select to authenticated
using(
  public.can_review()
  or exists(
    select 1 from public.observations o
    where o.id=observation_id and o.teacher_id=public.my_teacher_id()
  )
);
drop policy if exists "scores review write" on public.observation_scores;
create policy "scores review write" on public.observation_scores for all to authenticated using(public.can_review()) with check(public.can_review());

-- Notifications
drop policy if exists "notifications own read" on public.notifications;
create policy "notifications own read" on public.notifications for select to authenticated
using(recipient_user_id=auth.uid() or recipient_user_id is null);
drop policy if exists "notifications leadership create" on public.notifications;
create policy "notifications leadership create" on public.notifications for insert to authenticated
with check(public.is_manager());
drop policy if exists "notifications own update" on public.notifications;
create policy "notifications own update" on public.notifications for update to authenticated
using(recipient_user_id=auth.uid()) with check(recipient_user_id=auth.uid());

-- Private Storage. Metadata table RLS remains the source of document ownership.
drop policy if exists "teacher docs authenticated upload" on storage.objects;
create policy "teacher docs authenticated upload" on storage.objects for insert to authenticated
with check(bucket_id='teacher-documents' and (public.is_manager() or (storage.foldername(name))[1]=public.my_teacher_id()::text));
drop policy if exists "teacher docs authenticated read" on storage.objects;
create policy "teacher docs authenticated read" on storage.objects for select to authenticated
using(bucket_id='teacher-documents' and (public.is_manager() or (storage.foldername(name))[1]=public.my_teacher_id()::text));
drop policy if exists "teacher docs authenticated update" on storage.objects;
create policy "teacher docs authenticated update" on storage.objects for update to authenticated
using(bucket_id='teacher-documents' and (public.is_manager() or (storage.foldername(name))[1]=public.my_teacher_id()::text))
with check(bucket_id='teacher-documents' and (public.is_manager() or (storage.foldername(name))[1]=public.my_teacher_id()::text));

drop policy if exists "teacher docs authenticated delete" on storage.objects;
create policy "teacher docs authenticated delete" on storage.objects for delete to authenticated
using(bucket_id='teacher-documents' and (public.is_manager() or (storage.foldername(name))[1]=public.my_teacher_id()::text));

grant select,insert,update,delete on public.academic_terms,public.leave_requests,public.school_events,
public.exam_responsibilities,public.teacher_documents,public.development_plans,public.observation_rubrics,
public.observation_scores,public.notifications to authenticated;
grant usage,select on all sequences in schema public to authenticated;


-- Automatic notifications for leave decisions.
create or replace function public.notify_leave_decision()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.status is distinct from old.status and new.status in ('Approved','Rejected') then
    insert into public.notifications(recipient_user_id,title,message,category,priority,action_url)
    values(new.requested_by,'Leave request '||lower(new.status),
      'Your '||new.leave_type||' leave request from '||new.start_date||' to '||new.end_date||' was '||lower(new.status)||'.',
      'Leave',case when new.status='Rejected' then 'High' else 'Normal' end,'/leave');
  end if;
  return new;
end; $$;
drop trigger if exists leave_decision_notification on public.leave_requests;
create trigger leave_decision_notification after update on public.leave_requests
for each row execute function public.notify_leave_decision();
