alter table public.timetable_classes add column if not exists academic_year int not null default extract(year from current_date)::int;
alter table public.timetable_classes drop constraint if exists timetable_classes_name_key;
create unique index if not exists timetable_classes_name_year_key on public.timetable_classes(name,academic_year);
-- TeachTrack Planning, Conflict, Workflow, Quality & Promotion Upgrade
-- Run after advanced-features-upgrade.sql.

create table if not exists public.class_subject_requirements(
 id bigint generated by default as identity primary key,
 class_id bigint not null references public.timetable_classes(id) on delete cascade,
 teacher_id bigint not null references public.teachers(id) on delete cascade,
 subject text not null,
 periods_per_week int not null default 5 check(periods_per_week between 1 and 20),
 room text not null default '',
 priority int not null default 1 check(priority between 1 and 5),
 created_at timestamptz not null default now(),
 unique(class_id,subject)
);

create table if not exists public.approval_workflows(
 id bigint generated by default as identity primary key,
 name text not null unique,
 entity_type text not null,
 steps jsonb not null default '["section_head","vice_principal","principal"]'::jsonb,
 active boolean not null default true,
 created_at timestamptz not null default now()
);

create table if not exists public.approval_requests(
 id bigint generated by default as identity primary key,
 workflow_id bigint not null references public.approval_workflows(id) on delete cascade,
 entity_type text not null,
 entity_id bigint,
 title text not null,
 description text not null default '',
 requested_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
 current_step int not null default 0,
 status text not null default 'Pending' check(status in ('Pending','Approved','Rejected','Cancelled')),
 created_at timestamptz not null default now(),
 completed_at timestamptz
);

create table if not exists public.approval_actions(
 id bigint generated by default as identity primary key,
 request_id bigint not null references public.approval_requests(id) on delete cascade,
 actor_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
 actor_role text not null,
 action text not null check(action in ('Approved','Rejected','Commented')),
 comment text not null default '',
 created_at timestamptz not null default now()
);

create table if not exists public.school_year_promotions(
 id bigint generated by default as identity primary key,
 from_year int not null,
 to_year int not null,
 source_class_id bigint references public.timetable_classes(id) on delete set null,
 target_class_id bigint references public.timetable_classes(id) on delete set null,
 source_class_name text not null,
 target_class_name text not null,
 status text not null default 'Completed',
 promoted_by uuid default auth.uid() references auth.users(id) on delete set null,
 created_at timestamptz not null default now()
);

insert into public.approval_workflows(name,entity_type,steps) values
('Lesson Plan Approval','lesson_plan','["section_head","vice_principal"]'::jsonb),
('Leave Approval','leave','["vice_principal","principal"]'::jsonb),
('Training Approval','training','["section_head","vice_principal"]'::jsonb),
('General School Approval','general','["section_head","vice_principal","principal"]'::jsonb)
on conflict(name) do nothing;

alter table public.class_subject_requirements enable row level security;
alter table public.approval_workflows enable row level security;
alter table public.approval_requests enable row level security;
alter table public.approval_actions enable row level security;
alter table public.school_year_promotions enable row level security;

drop policy if exists "requirements read" on public.class_subject_requirements;
create policy "requirements read" on public.class_subject_requirements for select to authenticated using(true);
drop policy if exists "requirements leadership write" on public.class_subject_requirements;
create policy "requirements leadership write" on public.class_subject_requirements for all to authenticated
using(public.is_manager()) with check(public.is_manager());

drop policy if exists "workflows read" on public.approval_workflows;
create policy "workflows read" on public.approval_workflows for select to authenticated using(true);
drop policy if exists "workflows leadership write" on public.approval_workflows;
create policy "workflows leadership write" on public.approval_workflows for all to authenticated
using(public.is_manager()) with check(public.is_manager());

drop policy if exists "approval requests read" on public.approval_requests;
create policy "approval requests read" on public.approval_requests for select to authenticated
using(requested_by=auth.uid() or public.can_review());
drop policy if exists "approval requests create" on public.approval_requests;
create policy "approval requests create" on public.approval_requests for insert to authenticated
with check(requested_by=auth.uid());
drop policy if exists "approval requests reviewers update" on public.approval_requests;
create policy "approval requests reviewers update" on public.approval_requests for update to authenticated
using(public.can_review()) with check(public.can_review());

drop policy if exists "approval actions read" on public.approval_actions;
create policy "approval actions read" on public.approval_actions for select to authenticated
using(public.can_review() or exists(select 1 from public.approval_requests r where r.id=request_id and r.requested_by=auth.uid()));
drop policy if exists "approval actions review insert" on public.approval_actions;
create policy "approval actions review insert" on public.approval_actions for insert to authenticated
with check(public.can_review());

drop policy if exists "promotion read" on public.school_year_promotions;
create policy "promotion read" on public.school_year_promotions for select to authenticated using(true);
drop policy if exists "promotion leadership write" on public.school_year_promotions;
create policy "promotion leadership write" on public.school_year_promotions for all to authenticated
using(public.is_manager()) with check(public.is_manager());

grant select,insert,update,delete on public.class_subject_requirements,public.approval_workflows,
public.approval_requests,public.approval_actions,public.school_year_promotions to authenticated;
grant usage,select on all sequences in schema public to authenticated;
