-- TeachTrack Pro / Supabase schema
-- Run this once in Supabase SQL Editor on a new project.

create extension if not exists pgcrypto;

create type public.app_role as enum ('principal','vice_principal','section_head','reviewer','teacher');

create table public.teachers (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete set null,
  name text not null,
  initials text not null,
  subject text not null,
  department text not null,
  email text not null unique,
  experience integer not null default 0 check (experience >= 0),
  qualification text not null default '',
  skills text[] not null default '{}',
  join_date date not null default current_date,
  status text not null default 'Active' check (status in ('Active','Inactive','On Leave')),
  milestones text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role public.app_role not null default 'teacher',
  teacher_id bigint unique references public.teachers(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.attendance (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  date date not null,
  status text not null check (status in ('Present','Late','Absent')),
  arrival_time time,
  created_at timestamptz not null default now(),
  unique(teacher_id,date)
);

create table public.training (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  title text not null,
  provider text not null,
  date date not null,
  hours numeric(6,1) not null check(hours > 0),
  status text not null check(status in ('Completed','In Progress','Upcoming')),
  certificate_verified boolean not null default false,
  certificate_url text,
  created_at timestamptz not null default now()
);

create table public.feedback (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  source text not null check(source in ('Student','Peer','Management')),
  category text not null,
  rating integer not null check(rating between 1 and 5),
  comment text not null,
  date date not null default current_date,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.lessons (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  title text not null,
  subject text not null,
  grade text not null,
  date date not null,
  status text not null default 'Draft' check(status in ('Draft','Pending','Approved','Rejected')),
  objective text not null,
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.achievements (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  badge text not null,
  icon text not null default '🏆',
  description text not null,
  date date not null default current_date,
  awarded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.goals (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  title text not null,
  category text not null,
  target_value numeric not null default 100,
  current_value numeric not null default 0,
  unit text not null default '%',
  due_date date not null,
  status text not null default 'Active' check(status in ('Active','Completed','At Risk','Paused')),
  created_at timestamptz not null default now()
);

create table public.observations (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  observer_id uuid references auth.users(id) on delete set null,
  observer_name text not null,
  date date not null,
  rating numeric(2,1) not null check(rating between 1 and 5),
  focus_area text not null,
  notes text not null,
  status text not null default 'Completed' check(status in ('Scheduled','Completed','Follow-up')),
  created_at timestamptz not null default now()
);

create table public.development_recommendations (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  title text not null,
  recommendation text not null,
  priority text not null default 'Medium' check(priority in ('Low','Medium','High')),
  status text not null default 'Suggested' check(status in ('Suggested','Accepted','Completed','Dismissed')),
  created_at timestamptz not null default now()
);

create table public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default 'System',
  action text not null,
  entity_type text not null,
  entity_id bigint,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

-- Derived performance metrics are calculated by PostgreSQL views.
create or replace view public.teacher_metrics with (security_invoker=true) as
select t.id,
  coalesce((select round(100.0 * count(*) filter (where a.status in ('Present','Late')) / nullif(count(*),0),1) from public.attendance a where a.teacher_id=t.id),100) as attendance_score,
  coalesce((select round(avg(f.rating)::numeric,1) from public.feedback f where f.teacher_id=t.id),0) as feedback_score,
  coalesce((select sum(tr.hours) from public.training tr where tr.teacher_id=t.id and tr.status='Completed'),0) as training_hours,
  (select count(*) from public.lessons l where l.teacher_id=t.id) as lesson_count
from public.teachers t;

create or replace view public.teachers_dashboard with (security_invoker=true) as
select t.*,
  m.attendance_score,m.feedback_score,m.training_hours,m.lesson_count,
  round((m.attendance_score * .45 + (m.feedback_score/5*100) * .35 + least(m.training_hours,40)/40*100 * .20)::numeric,1) as performance_score
from public.teachers t join public.teacher_metrics m on m.id=t.id;

-- New Auth users automatically receive a safe teacher role profile.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,full_name,role)
  values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),'teacher')
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.current_role() returns public.app_role
language sql stable security definer set search_path=public as $$
  select role from public.profiles where id=auth.uid();
$$;

create or replace function public.has_role(allowed public.app_role[]) returns boolean
language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.profiles p
    where p.id=auth.uid() and p.role = any(allowed)
  );
$$;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path=public as $$
  select public.has_role(array['principal']::public.app_role[]);
$$;

create or replace function public.is_manager() returns boolean
language sql stable security definer set search_path=public as $$
  select public.has_role(array['principal','vice_principal']::public.app_role[]);
$$;

create or replace function public.can_review() returns boolean
language sql stable security definer set search_path=public as $$
  select public.has_role(array['principal','vice_principal','section_head','reviewer']::public.app_role[]);
$$;

create or replace function public.my_teacher_id() returns bigint
language sql stable security definer set search_path=public as $$
  select teacher_id from public.profiles where id=auth.uid();
$$;


-- User-control RPC. Authenticated leadership can change application roles without
-- exposing auth.users or allowing direct profile-role edits.
create or replace function public.set_user_role(target_user uuid, new_role public.app_role)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  caller_role public.app_role;
begin
  select role into caller_role from public.profiles where id=auth.uid();

  if caller_role='principal' then
    if new_role not in ('principal','vice_principal','section_head','reviewer','teacher') then
      raise exception 'Role not allowed';
    end if;
  elsif caller_role='vice_principal' then
    if new_role not in ('section_head','reviewer','teacher') then
      raise exception 'Vice Principal cannot assign this role';
    end if;
    if exists(select 1 from public.profiles where id=target_user and role in ('principal','vice_principal')) then
      raise exception 'Vice Principal cannot modify Principal or Vice Principal accounts';
    end if;
  else
    raise exception 'Not authorized';
  end if;

  if target_user=auth.uid() then
    raise exception 'You cannot change your own role';
  end if;

  update public.profiles set role=new_role where id=target_user;
  if not found then raise exception 'User profile not found'; end if;

  insert into public.activity_logs(actor_id,actor_name,action,entity_type,metadata)
  select auth.uid(),coalesce(p.full_name,'Leadership user'),'Changed user role','profile',
         jsonb_build_object('target_user',target_user,'new_role',new_role::text)
  from public.profiles p where p.id=auth.uid();
end;
$$;

grant execute on function public.set_user_role(uuid, public.app_role) to authenticated;

-- Row Level Security
alter table public.profiles enable row level security;
alter table public.teachers enable row level security;
alter table public.attendance enable row level security;
alter table public.training enable row level security;
alter table public.feedback enable row level security;
alter table public.lessons enable row level security;
alter table public.achievements enable row level security;
alter table public.goals enable row level security;
alter table public.observations enable row level security;
alter table public.development_recommendations enable row level security;
alter table public.activity_logs enable row level security;

create policy "profile self or admin read" on public.profiles for select to authenticated using (id=auth.uid() or public.is_manager());

create policy "teachers admin or self read" on public.teachers for select to authenticated using (public.is_manager() or id=public.my_teacher_id());
create policy "teachers admin insert" on public.teachers for insert to authenticated with check (public.is_manager());
create policy "teachers admin update" on public.teachers for update to authenticated using (public.is_manager()) with check (public.is_manager());
create policy "teachers admin delete" on public.teachers for delete to authenticated using (public.is_manager());

create policy "attendance admin or self read" on public.attendance for select to authenticated using (public.is_manager() or teacher_id=public.my_teacher_id());
create policy "attendance admin write" on public.attendance for all to authenticated using (public.is_manager()) with check (public.is_manager());

create policy "training admin or self read" on public.training for select to authenticated using (public.is_manager() or teacher_id=public.my_teacher_id());
create policy "training admin write" on public.training for all to authenticated using (public.is_manager()) with check (public.is_manager());

create policy "feedback admin or self read" on public.feedback for select to authenticated using (public.is_manager() or teacher_id=public.my_teacher_id());
create policy "feedback leadership insert" on public.feedback for insert to authenticated with check (public.is_manager() and created_by=auth.uid());
create policy "feedback admin manage" on public.feedback for update to authenticated using (public.is_manager()) with check (public.is_manager());
create policy "feedback admin delete" on public.feedback for delete to authenticated using (public.is_manager());

create policy "lessons reviewer or self read" on public.lessons for select to authenticated using (public.can_review() or teacher_id=public.my_teacher_id());
create policy "lessons self insert" on public.lessons for insert to authenticated with check (public.is_manager() or teacher_id=public.my_teacher_id());
create policy "lessons self draft update" on public.lessons for update to authenticated using (public.is_manager() or teacher_id=public.my_teacher_id()) with check (public.is_admin() or (teacher_id=public.my_teacher_id() and status in ('Draft','Pending')));
create policy "lessons admin delete" on public.lessons for delete to authenticated using (public.is_manager());

create policy "achievements admin or self read" on public.achievements for select to authenticated using (public.is_manager() or teacher_id=public.my_teacher_id());
create policy "achievements admin write" on public.achievements for all to authenticated using (public.is_manager()) with check (public.is_manager());

create policy "goals admin or self read" on public.goals for select to authenticated using (public.is_manager() or teacher_id=public.my_teacher_id());
create policy "goals admin or self insert" on public.goals for insert to authenticated with check (public.is_manager() or teacher_id=public.my_teacher_id());
create policy "goals admin or self update" on public.goals for update to authenticated using (public.is_manager() or teacher_id=public.my_teacher_id()) with check (public.is_manager() or teacher_id=public.my_teacher_id());
create policy "goals admin delete" on public.goals for delete to authenticated using (public.is_manager());

create policy "observations admin or self read" on public.observations for select to authenticated using (public.is_manager() or teacher_id=public.my_teacher_id());
create policy "observations admin write" on public.observations for all to authenticated using (public.is_manager()) with check (public.is_manager());

create policy "development admin or self read" on public.development_recommendations for select to authenticated using (public.is_manager() or teacher_id=public.my_teacher_id());
create policy "development admin write" on public.development_recommendations for all to authenticated using (public.is_manager()) with check (public.is_manager());

create policy "activity admin read" on public.activity_logs for select to authenticated using (public.is_manager());
create policy "activity authenticated insert" on public.activity_logs for insert to authenticated with check (actor_id=auth.uid());

-- Private Storage bucket for certificates.
insert into storage.buckets(id,name,public) values('certificates','certificates',false)
on conflict(id) do nothing;

create policy "certificate owner or admin read" on storage.objects for select to authenticated
using (bucket_id='certificates' and (public.is_admin() or (storage.foldername(name))[1]=public.my_teacher_id()::text));
create policy "certificate owner or admin upload" on storage.objects for insert to authenticated
with check (bucket_id='certificates' and (public.is_admin() or (storage.foldername(name))[1]=public.my_teacher_id()::text));
create policy "certificate admin manage" on storage.objects for update to authenticated using (bucket_id='certificates' and public.is_admin()) with check (bucket_id='certificates' and public.is_admin());
create policy "certificate admin delete" on storage.objects for delete to authenticated using (bucket_id='certificates' and public.is_admin());

grant usage on schema public to authenticated;
grant select on public.teachers_dashboard, public.teacher_metrics to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;


-- TeachTrack Timetable Module
-- Run in Supabase SQL Editor AFTER the main schema/RBAC migrations.

create table if not exists public.school_periods (
  id smallint primary key,
  label text not null,
  start_time time not null,
  end_time time not null,
  is_interval boolean not null default false,
  sort_order smallint not null unique
);

insert into public.school_periods(id,label,start_time,end_time,is_interval,sort_order) values
(1,'Period 1','07:50','08:30',false,1),
(2,'Period 2','08:30','09:10',false,2),
(3,'Period 3','09:10','09:50',false,3),
(4,'Period 4','09:50','10:30',false,4),
(5,'Interval','10:30','10:50',true,5),
(6,'Period 5','10:50','11:30',false,6),
(7,'Period 6','11:30','12:10',false,7),
(8,'Period 7','12:10','12:50',false,8),
(9,'Period 8','12:50','13:30',false,9)
on conflict(id) do update set
 label=excluded.label,start_time=excluded.start_time,end_time=excluded.end_time,
 is_interval=excluded.is_interval,sort_order=excluded.sort_order;

create table if not exists public.timetable_classes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  grade text not null,
  section text not null default '',
  medium text not null default 'English' check (medium in ('Sinhala','Tamil','English')),
  class_teacher_id bigint references public.teachers(id) on delete set null,
  room text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.timetable_entries (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.timetable_classes(id) on delete cascade,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  day_of_week smallint not null check(day_of_week between 1 and 5),
  period_id smallint not null references public.school_periods(id),
  subject text not null,
  room text not null default '',
  notes text not null default '',
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(class_id, day_of_week, period_id)
);

create table if not exists public.timetable_substitutions (
  id bigint generated by default as identity primary key,
  timetable_entry_id bigint not null references public.timetable_entries(id) on delete cascade,
  date date not null,
  original_teacher_id bigint not null references public.teachers(id) on delete cascade,
  substitute_teacher_id bigint not null references public.teachers(id) on delete cascade,
  reason text not null default '',
  status text not null default 'Assigned' check(status in ('Assigned','Completed','Cancelled')),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(timetable_entry_id,date)
);

-- Database-level clash protection.
create or replace function public.check_timetable_clash()
returns trigger
language plpgsql
set search_path=public
as $$
declare
  p_interval boolean;
begin
  select is_interval into p_interval from public.school_periods where id=new.period_id;
  if p_interval then
    raise exception 'Lessons cannot be assigned during the interval';
  end if;

  if exists(
    select 1 from public.timetable_entries e
    where e.teacher_id=new.teacher_id
      and e.day_of_week=new.day_of_week
      and e.period_id=new.period_id
      and e.id<>coalesce(new.id,0)
  ) then
    raise exception 'Teacher clash: this teacher already has a lesson in that period';
  end if;

  if nullif(trim(new.room),'') is not null and exists(
    select 1 from public.timetable_entries e
    where lower(trim(e.room))=lower(trim(new.room))
      and e.day_of_week=new.day_of_week
      and e.period_id=new.period_id
      and e.id<>coalesce(new.id,0)
  ) then
    raise exception 'Room clash: this room is already occupied in that period';
  end if;

  return new;
end;
$$;

drop trigger if exists timetable_clash_guard on public.timetable_entries;
create trigger timetable_clash_guard
before insert or update on public.timetable_entries
for each row execute function public.check_timetable_clash();

create or replace function public.check_substitute_clash()
returns trigger
language plpgsql
set search_path=public
as $$
declare
  v_day smallint;
  v_period smallint;
begin
  v_day := extract(isodow from new.date)::smallint;
  select period_id into v_period from public.timetable_entries where id=new.timetable_entry_id;

  if v_day between 1 and 5 and exists(
    select 1 from public.timetable_entries e
    where e.teacher_id=new.substitute_teacher_id
      and e.day_of_week=v_day
      and e.period_id=v_period
  ) then
    raise exception 'Substitute clash: this teacher already teaches during that period';
  end if;

  return new;
end;
$$;

drop trigger if exists substitute_clash_guard on public.timetable_substitutions;
create trigger substitute_clash_guard
before insert or update on public.timetable_substitutions
for each row execute function public.check_substitute_clash();

alter table public.school_periods enable row level security;
alter table public.timetable_classes enable row level security;
alter table public.timetable_entries enable row level security;
alter table public.timetable_substitutions enable row level security;

drop policy if exists "periods authenticated read" on public.school_periods;
create policy "periods authenticated read" on public.school_periods
for select to authenticated using (true);

drop policy if exists "classes authenticated read" on public.timetable_classes;
create policy "classes authenticated read" on public.timetable_classes
for select to authenticated using (true);

drop policy if exists "classes leadership write" on public.timetable_classes;
create policy "classes leadership write" on public.timetable_classes
for all to authenticated using (public.is_manager()) with check (public.is_manager());

drop policy if exists "timetable leadership or own read" on public.timetable_entries;
create policy "timetable leadership or own read" on public.timetable_entries
for select to authenticated
using (public.is_manager() or teacher_id=public.my_teacher_id());

drop policy if exists "timetable leadership write" on public.timetable_entries;
create policy "timetable leadership write" on public.timetable_entries
for all to authenticated using (public.is_manager()) with check (public.is_manager());

drop policy if exists "substitution leadership or own read" on public.timetable_substitutions;
create policy "substitution leadership or own read" on public.timetable_substitutions
for select to authenticated
using (
  public.is_manager()
  or original_teacher_id=public.my_teacher_id()
  or substitute_teacher_id=public.my_teacher_id()
);

drop policy if exists "substitution leadership write" on public.timetable_substitutions;
create policy "substitution leadership write" on public.timetable_substitutions
for all to authenticated using (public.is_manager()) with check (public.is_manager());

grant select on public.school_periods to authenticated;
grant select,insert,update,delete on public.timetable_classes,public.timetable_entries,public.timetable_substitutions to authenticated;
grant usage,select on all sequences in schema public to authenticated;
