-- TeachTrack Timetable Module
-- Run in Supabase SQL Editor AFTER the main schema/RBAC migrations.

create table if not exists public.school_periods (
  id smallint primary key,
  label text not null,
  start_time time not null,
  end_time time not null,
  is_interval boolean not null default false,
  sort_order smallint not null unique
);

insert into public.school_periods(id,label,start_time,end_time,is_interval,sort_order) values
(1,'Period 1','07:50','08:30',false,1),
(2,'Period 2','08:30','09:10',false,2),
(3,'Period 3','09:10','09:50',false,3),
(4,'Period 4','09:50','10:30',false,4),
(5,'Interval','10:30','10:50',true,5),
(6,'Period 5','10:50','11:30',false,6),
(7,'Period 6','11:30','12:10',false,7),
(8,'Period 7','12:10','12:50',false,8),
(9,'Period 8','12:50','13:30',false,9)
on conflict(id) do update set
 label=excluded.label,start_time=excluded.start_time,end_time=excluded.end_time,
 is_interval=excluded.is_interval,sort_order=excluded.sort_order;

create table if not exists public.timetable_classes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  grade text not null,
  section text not null default '',
  medium text not null default 'English' check (medium in ('Sinhala','Tamil','English')),
  class_teacher_id bigint references public.teachers(id) on delete set null,
  room text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.timetable_entries (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.timetable_classes(id) on delete cascade,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  day_of_week smallint not null check(day_of_week between 1 and 5),
  period_id smallint not null references public.school_periods(id),
  subject text not null,
  room text not null default '',
  notes text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(class_id, day_of_week, period_id)
);

create table if not exists public.timetable_substitutions (
  id bigint generated by default as identity primary key,
  timetable_entry_id bigint not null references public.timetable_entries(id) on delete cascade,
  date date not null,
  original_teacher_id bigint not null references public.teachers(id) on delete cascade,
  substitute_teacher_id bigint not null references public.teachers(id) on delete cascade,
  reason text not null default '',
  status text not null default 'Assigned' check(status in ('Assigned','Completed','Cancelled')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(timetable_entry_id,date)
);

-- Database-level clash protection.
create or replace function public.check_timetable_clash()
returns trigger
language plpgsql
set search_path=public
as $$
declare
  p_interval boolean;
begin
  select is_interval into p_interval from public.school_periods where id=new.period_id;
  if p_interval then
    raise exception 'Lessons cannot be assigned during the interval';
  end if;

  if exists(
    select 1 from public.timetable_entries e
    where e.teacher_id=new.teacher_id
      and e.day_of_week=new.day_of_week
      and e.period_id=new.period_id
      and e.id<>coalesce(new.id,0)
  ) then
    raise exception 'Teacher clash: this teacher already has a lesson in that period';
  end if;

  if nullif(trim(new.room),'') is not null and exists(
    select 1 from public.timetable_entries e
    where lower(trim(e.room))=lower(trim(new.room))
      and e.day_of_week=new.day_of_week
      and e.period_id=new.period_id
      and e.id<>coalesce(new.id,0)
  ) then
    raise exception 'Room clash: this room is already occupied in that period';
  end if;

  return new;
end;
$$;

drop trigger if exists timetable_clash_guard on public.timetable_entries;
create trigger timetable_clash_guard
before insert or update on public.timetable_entries
for each row execute function public.check_timetable_clash();

create or replace function public.check_substitute_clash()
returns trigger
language plpgsql
set search_path=public
as $$
declare
  v_day smallint;
  v_period smallint;
begin
  v_day := extract(isodow from new.date)::smallint;
  select period_id into v_period from public.timetable_entries where id=new.timetable_entry_id;

  if v_day between 1 and 5 and exists(
    select 1 from public.timetable_entries e
    where e.teacher_id=new.substitute_teacher_id
      and e.day_of_week=v_day
      and e.period_id=v_period
  ) then
    raise exception 'Substitute clash: this teacher already teaches during that period';
  end if;

  return new;
end;
$$;

drop trigger if exists substitute_clash_guard on public.timetable_substitutions;
create trigger substitute_clash_guard
before insert or update on public.timetable_substitutions
for each row execute function public.check_substitute_clash();

alter table public.school_periods enable row level security;
alter table public.timetable_classes enable row level security;
alter table public.timetable_entries enable row level security;
alter table public.timetable_substitutions enable row level security;

drop policy if exists "periods authenticated read" on public.school_periods;
create policy "periods authenticated read" on public.school_periods
for select to authenticated using (true);

drop policy if exists "classes authenticated read" on public.timetable_classes;
create policy "classes authenticated read" on public.timetable_classes
for select to authenticated using (true);

drop policy if exists "classes leadership write" on public.timetable_classes;
create policy "classes leadership write" on public.timetable_classes
for all to authenticated using (public.is_manager()) with check (public.is_manager());

drop policy if exists "timetable leadership or own read" on public.timetable_entries;
create policy "timetable leadership or own read" on public.timetable_entries
for select to authenticated
using (public.is_manager() or teacher_id=public.my_teacher_id());

drop policy if exists "timetable leadership write" on public.timetable_entries;
create policy "timetable leadership write" on public.timetable_entries
for all to authenticated using (public.is_manager()) with check (public.is_manager());

drop policy if exists "substitution leadership or own read" on public.timetable_substitutions;
create policy "substitution leadership or own read" on public.timetable_substitutions
for select to authenticated
using (
  public.is_manager()
  or original_teacher_id=public.my_teacher_id()
  or substitute_teacher_id=public.my_teacher_id()
);

drop policy if exists "substitution leadership write" on public.timetable_substitutions;
create policy "substitution leadership write" on public.timetable_substitutions
for all to authenticated using (public.is_manager()) with check (public.is_manager());

grant select on public.school_periods to authenticated;
grant select,insert,update,delete on public.timetable_classes,public.timetable_entries,public.timetable_substitutions to authenticated;
grant usage,select on all sequences in schema public to authenticated;
