'use client'
import { useData } from '@/components/DataProvider'
export default function Security(){
 const {data,loading,role}=useData();if(loading)return <div className="loading">Loading audit centre…</div>
 if(!['principal','vice_principal','section_head','reviewer'].includes(role))return <div className="panel empty">Audit & Security is available to authorized school leadership and reviewers.</div>
 const logins=[...(data.login_events||[])].sort((a:any,b:any)=>String(b.signed_in_at).localeCompare(String(a.signed_in_at)));const logs=[...(data.activity_logs||[])].sort((a:any,b:any)=>String(b.created_at).localeCompare(String(a.created_at)))
 const roleChanges=logs.filter((x:any)=>String(x.action).toLowerCase().includes('role')).length
 const destructive=logs.filter((x:any)=>String(x.action).toLowerCase().includes('deleted')).length
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>Audit & security centre</span><h1 style={{marginTop:14}}>Security activity</h1><p>Review important platform changes and role-sensitive actions recorded by TeachTrack.</p></div></div><div className="kpis"><div className="kpi"><small>AUDIT EVENTS</small><b>{logs.length}</b><span>Recorded actions</span></div><div className="kpi"><small>ROLE CHANGES</small><b>{roleChanges}</b><span>Permission events</span></div><div className="kpi"><small>DELETE ACTIONS</small><b>{destructive}</b><span>Destructive events</span></div><div className="kpi"><small>LOGIN EVENTS</small><b>{logins.length}</b><span>Visible sign-ins</span></div></div>
 <div className="grid-2"><section className="panel"><div className="panel-head"><div><h3>Recent login activity</h3><p>Successful authenticated sessions recorded by TeachTrack.</p></div></div>{logins.slice(0,12).map((l:any)=><div className="metric" key={l.id}><span>{l.client_note}</span><b>{new Date(l.signed_in_at).toLocaleString('en-GB',{timeZone:'Asia/Colombo'})}</b></div>)}{!logins.length&&<div className="empty">No login events yet.</div>}</section><section className="panel"><div className="panel-head"><div><h3>Security posture</h3><p>Current access model</p></div></div><div className="metric"><span>Your role</span><b>{role}</b></div><div className="metric"><span>Row Level Security</span><b>Enabled</b></div><div className="metric"><span>CMS access</span><b>Role guarded</b></div><div className="metric"><span>Document storage</span><b>Private</b></div></section></div><section className="panel" style={{marginTop:18}}><div className="table-wrap"><table className="table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th><th>Entity ID</th></tr></thead><tbody>{logs.slice(0,100).map((r:any)=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString('en-GB',{timeZone:'Asia/Colombo'})}</td><td>{r.actor_name}</td><td>{r.action}</td><td>{r.entity_type}</td><td>{r.entity_id||'—'}</td></tr>)}</tbody></table>{!logs.length&&<div className="empty">No audit events recorded.</div>}</div></section></>
}
