'use client'
import { FormEvent,useState } from 'react'
import { useData } from '@/components/DataProvider'
import { TeacherPicker } from '@/components/TeacherPicker'
export default function SkillsMatrix(){
 const{data,loading,role,insert}=useData();const[msg,setMsg]=useState('');const leadership=['principal','vice_principal','section_head','reviewer'].includes(role);if(loading)return <div className="loading">Building skills matrix…</div>
 if(!['principal','vice_principal','section_head','reviewer'].includes(role))return <div className="panel empty">Skills Matrix is available to school leadership and reviewers.</div>
 const teachers=data.teachers_dashboard||[],rows=data.teacher_skill_evidence||[],skills=[...new Set([...rows.map((x:any)=>x.skill),...teachers.flatMap((t:any)=>t.skills||[])])].slice(0,16)
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await insert('teacher_skill_evidence',{teacher_id:Number(f.get('teacher_id')),skill:String(f.get('skill')),level:Number(f.get('level')),evidence:String(f.get('evidence')||''),reviewed_at:new Date().toISOString().slice(0,10)});setMsg('Skill evidence saved.')}catch(err:any){setMsg(err.message)}}
 const gaps=skills.map(skill=>{const vals=teachers.map((t:any)=>rows.find((x:any)=>String(x.teacher_id)===String(t.id)&&x.skill===skill)?.level||((t.skills||[]).includes(skill)?3:0));return {skill,avg:vals.length?vals.reduce((a:number,b:number)=>a+Number(b),0)/vals.length:0,coverage:vals.filter((x:any)=>Number(x)>0).length}}).sort((a:any,b:any)=>a.avg-b.avg)
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>Capability planning</span><h1 style={{marginTop:14}}>Teacher skills matrix</h1><p>Identify strengths, mentoring opportunities and school-wide development gaps.</p></div></div>{msg&&<div className="command"><div><b>{msg}</b></div><i className="pulse"/></div>}
 {leadership&&<section className="panel" style={{marginTop:18}}><form className="form-grid" onSubmit={add}><div className="field"><label>TEACHER</label><TeacherPicker name="teacher_id" required/></div><div className="field"><label>SKILL</label><input name="skill" list="skill-suggestions" required/><datalist id="skill-suggestions">{['Classroom Management','ICT','Assessment','Communication','Leadership','Inclusive Education','Mentoring'].map(x=><option value={x} key={x}/>)}</datalist></div><div className="field"><label>LEVEL 1–5</label><input name="level" type="number" min="1" max="5" defaultValue="3" required/></div><div className="field full"><label>EVIDENCE</label><input name="evidence"/></div><button className="btn btn-primary full">Save skill evidence</button></form></section>}
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h3>School skills gap analysis</h3><p>Lowest average evidence areas are shown first.</p></div></div><div className="kpis">{gaps.slice(0,4).map((g:any)=><div className="kpi" key={g.skill}><small>{g.skill.toUpperCase()}</small><b>{g.avg.toFixed(1)}/5</b><span>{g.coverage}/{teachers.length} teachers evidenced</span></div>)}</div></section>
 <section className="panel" style={{marginTop:18}}><div className="table-wrap"><table className="table skill-table"><thead><tr><th>Teacher</th>{skills.map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{teachers.map((t:any)=><tr key={t.id}><td><b>{t.name}</b></td>{skills.map(s=>{const r=rows.find((x:any)=>String(x.teacher_id)===String(t.id)&&x.skill===s);const listed=(t.skills||[]).includes(s);return <td key={s}>{r?`${r.level}/5`:listed?'✓':'—'}</td>})}</tr>)}</tbody></table></div></section></>
}