'use client'
import { useState } from 'react'
import { Plus } from 'lucide-react'
import { useData } from '@/components/DataProvider'
import { TeacherPicker } from '@/components/TeacherPicker'
export default function Exams(){
 const {data,loading,role,insert}=useData();const[open,setOpen]=useState(false);const[msg,setMsg]=useState('');const leadership=['principal','vice_principal'].includes(role)
 const rows=data.exam_responsibilities||[],teachers=data.teachers_dashboard||[];const teacher=(id:any)=>teachers.find((t:any)=>String(t.id)===String(id))
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{await insert('exam_responsibilities',{teacher_id:Number(fd.get('teacher_id')),exam_name:String(fd.get('exam_name')),responsibility:String(fd.get('responsibility')),subject:String(fd.get('subject')||''),grade:String(fd.get('grade')||''),due_date:String(fd.get('due_date')||'')||null,duty_date:String(fd.get('duty_date')||'')||null,start_time:String(fd.get('start_time')||'')||null,end_time:String(fd.get('end_time')||'')||null,location:String(fd.get('location')||''),status:'Assigned',notes:String(fd.get('notes')||'')});setOpen(false);setMsg('Exam responsibility assigned and available to Conflict Detection.')}catch(err:any){setMsg(err.message)}}
 if(loading)return <div className="loading">Loading exam duties…</div>
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>Assessment operations</span><h1 style={{marginTop:14}}>Exam responsibilities</h1><p>Track paper setting, moderation, invigilation, marking and scheduled duties. Timed duties are automatically scanned for conflicts.</p></div>{leadership&&<button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={16}/> Assign duty</button>}</div>
 {msg&&<div className="command" style={{marginBottom:18}}><div><small>STATUS</small><b>{msg}</b></div><i className="pulse"/></div>}
 <section className="panel"><div className="table-wrap"><table className="table"><thead><tr><th>Teacher</th><th>Exam</th><th>Responsibility</th><th>Schedule</th><th>Location</th><th>Due</th><th>Status</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td>{teacher(r.teacher_id)?.name||'Teacher'}<small style={{display:'block'}}>{teacher(r.teacher_id)?.teacher_code||''}</small></td><td>{r.exam_name}<small style={{display:'block'}}>{r.subject||'—'} · {r.grade||'—'}</small></td><td>{r.responsibility}</td><td>{r.duty_date?`${r.duty_date}${r.start_time?` · ${String(r.start_time).slice(0,5)}–${String(r.end_time||'').slice(0,5)}`:''}`:'Not timed'}</td><td>{r.location||'—'}</td><td>{r.due_date||'—'}</td><td><span className="status good">{r.status}</span></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No exam duties assigned.</div>}</div></section>
 {open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><div className="modal" role="dialog" aria-modal="true"><div className="panel-head"><div><small>EXAM DUTY</small><h2>Assign responsibility</h2></div><button className="btn" onClick={()=>setOpen(false)}>Close</button></div><form onSubmit={submit} className="form-grid">
 <div className="field full"><label>TEACHER</label><TeacherPicker name="teacher_id" required={false} allowEmpty={true} placeholder="Search teacher code, ID or name…"/></div>
 <div className="field"><label>EXAM</label><input name="exam_name" required placeholder="Term 2 Examination"/></div><div className="field"><label>RESPONSIBILITY</label><select name="responsibility"><option>Paper Setting</option><option>Moderation</option><option>Invigilation</option><option>Marking</option><option>Results</option><option>Other</option></select></div>
 <div className="field"><label>SUBJECT</label><input name="subject"/></div><div className="field"><label>GRADE</label><input name="grade" placeholder="Grade 10"/></div>
 <div className="field"><label>DUTY DATE</label><input type="date" name="duty_date"/></div><div className="field"><label>LOCATION</label><input name="location" placeholder="Main Hall"/></div>
 <div className="field"><label>START TIME</label><input type="time" name="start_time"/></div><div className="field"><label>END TIME</label><input type="time" name="end_time"/></div>
 <div className="field"><label>ADMIN DUE DATE</label><input type="date" name="due_date"/></div><div className="field full"><label>NOTES</label><textarea name="notes" rows={3}/></div><button className="btn btn-primary full">Assign duty</button></form></div></div>}
 </>}
