'use client'
import { useData } from '@/components/DataProvider'
import { inSchoolContext,useSchoolContext } from '@/components/useSchoolContext'
import { BarChart,Bar,CartesianGrid,Legend,LineChart,Line,PieChart,Pie,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts'
export default function Analytics(){
 const{loading,data}=useData();const{academicYear,term}=useSchoolContext();if(loading)return <div className="loading">Calculating analytics…</div>
 const terms=data.academic_terms||[],scoped=(name:string)=>(data[name]||[]).filter((x:any)=>inSchoolContext(x,academicYear,term,terms))
 const teachers=(data.teachers_dashboard||[]).map((t:any)=>({name:t.teacher_code||t.name,fullName:t.name,performance:Number(t.performance_score||0),attendance:Number(t.attendance_score||0),feedback:Number(t.feedback_score||0)*20}))
 const attendance=['Present','Late','Absent'].map(s=>({name:s,value:scoped('attendance').filter((a:any)=>a.status===s).length}))
 const months:Record<string,{month:string,feedback:number,count:number}>={}
 scoped('feedback').forEach((f:any)=>{const m=String(f.date||f.created_at).slice(0,7);months[m]??={month:m,feedback:0,count:0};months[m].feedback+=Number(f.rating);months[m].count++})
 const trend=Object.values(months).sort((a,b)=>a.month.localeCompare(b.month)).map(x=>({month:x.month,feedback:Number((x.feedback/x.count).toFixed(2))}))
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>Visual analytics</span><h1>Performance intelligence</h1><p>Interactive trends scoped to {academicYear} · {term} using the global academic filter.</p></div><span className="status good">Live calculations</span></div><div className="grid-2"><section className="panel"><div className="panel-head"><div><h3>Teacher performance</h3><p>Composite score and attendance</p></div></div><div style={{height:350,overflowX:'auto',overflowY:'hidden'}}><div style={{width:Math.max(720,teachers.length*62),height:330}}><ResponsiveContainer width="100%" height="100%"><BarChart data={teachers} margin={{bottom:48,left:0,right:8,top:8}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" interval={0} angle={-35} textAnchor="end" height={68} tick={{fontSize:11}}/><YAxis domain={[0,100]}/><Tooltip formatter={(value:any,name:any)=>[value,name]} labelFormatter={(label:any)=>teachers.find((t:any)=>t.name===label)?.fullName||label}/><Legend/><Bar dataKey="performance" fill="#061a38" radius={[5,5,0,0]}/><Bar dataKey="attendance" fill="#16a9c4" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div></section><section className="panel"><div className="panel-head"><div><h3>Attendance mix</h3><p>{academicYear} · {term}</p></div></div><div style={{height:330}}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={attendance} dataKey="value" nameKey="name" outerRadius={105} fill="#061a38" label/><Tooltip/><Legend/></PieChart></ResponsiveContainer></div></section></div><section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h3>Feedback trend</h3><p>Average rating by month</p></div></div><div style={{height:320}}><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis domain={[0,5]}/><Tooltip/><Line type="monotone" dataKey="feedback" stroke="#b62419" strokeWidth={3}/></LineChart></ResponsiveContainer></div></section></>
}
