'use client'
import { useMemo,useState } from 'react'
import { useData } from '@/components/DataProvider'
import { workloadScore } from '@/lib/advancedUx'
export default function SubstitutionAssistant(){
 const{data,loading,role,insert}=useData();const[entryId,setEntryId]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[msg,setMsg]=useState('')
 const entries=data.timetable_entries||[],teachers=data.teachers_dashboard||[],chosen=entries.find((x:any)=>String(x.id)===entryId)
 const ranked=useMemo(()=>{if(!chosen)return[];return teachers.filter((t:any)=>String(t.id)!==String(chosen.teacher_id)&&!entries.some((e:any)=>String(e.teacher_id)===String(t.id)&&Number(e.day_of_week)===Number(chosen.day_of_week)&&Number(e.period_id)===Number(chosen.period_id))).map((t:any)=>{const w=workloadScore(data,t.id),subject=String(t.subject||'').toLowerCase()===String(chosen.subject||'').toLowerCase();return {...t,workload:w.total,score:(subject?60:0)+Math.max(0,40-w.total),subject}}).sort((a:any,b:any)=>b.score-a.score).slice(0,10)},[chosen,teachers,entries,data])
 if(loading)return <div className="loading">Ranking substitute options…</div>
 if(!['principal','vice_principal','section_head','reviewer'].includes(role))return <div className="panel empty">Substitute Assistant is available to school leadership and reviewers.</div>
 async function assign(t:any){if(!chosen)return;try{await insert('timetable_substitutions',{timetable_entry_id:Number(chosen.id),date,original_teacher_id:Number(chosen.teacher_id),substitute_teacher_id:Number(t.id),reason:'Assigned through ranked substitute assistant',status:'Assigned'});setMsg(`${t.name} assigned.`)}catch(err:any){setMsg(err.message)}}
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>Ranked cover assistant</span><h1 style={{marginTop:14}}>Substitute recommendation panel</h1><p>Choose from several ranked teachers using subject compatibility, availability and current workload.</p></div></div>{msg&&<div className="command"><div><b>{msg}</b></div><i className="pulse"/></div>}<section className="panel" style={{marginTop:18}}><div className="form-grid"><div className="field"><label>TIMETABLE ENTRY</label><select value={entryId} onChange={e=>setEntryId(e.target.value)}><option value="">Choose lesson</option>{entries.map((e:any)=><option key={e.id} value={e.id}>{e.subject} · day {e.day_of_week} · period {e.period_id}</option>)}</select></div><div className="field"><label>DATE</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div>{ranked.map((t:any,i)=><div className="queue-row" key={t.id}><div><b>#{i+1} {t.name} {t.subject?'· '+t.subject:''}</b><small>{t.subject?'Subject '+(t.subject?'match':''):''} · workload {t.workload} · recommendation score {t.score}</small></div><button className="btn btn-primary" onClick={()=>assign(t)}>Assign</button></div>)}{chosen&&!ranked.length&&<div className="empty">No available teachers for this period.</div>}</section></>
}