'use client'
import { FormEvent,useState } from 'react'
import { useData } from '@/components/DataProvider'
import { TeacherPicker } from '@/components/TeacherPicker'
import { composite } from '@/lib/teacherInsights'
export default function Mentoring(){
 const{data,loading,role,insert}=useData();const[msg,setMsg]=useState('');const[sessionPair,setSessionPair]=useState('');const leadership=['principal','vice_principal','section_head','reviewer'].includes(role);if(loading)return <div className="loading">Loading mentoring…</div>
 const teachers=data.teachers_dashboard||[],pairs=data.mentoring_pairs||[],sessions=data.mentoring_sessions||[]
 const suggestions=[...teachers].sort((a:any,b:any)=>Number(b.experience||0)-Number(a.experience||0)||composite(data,b).score-composite(data,a).score).slice(0,8)
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await insert('mentoring_pairs',{mentor_teacher_id:Number(f.get('mentor_teacher_id')),mentee_teacher_id:Number(f.get('mentee_teacher_id')),focus_area:String(f.get('focus_area')||''),start_date:String(f.get('start_date')),status:'Active'});setMsg('Mentoring pair created.')}catch(err:any){setMsg(err.message)}}
 async function addSession(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await insert('mentoring_sessions',{pair_id:Number(f.get('pair_id')),session_date:String(f.get('session_date')),objective:String(f.get('objective')),notes:String(f.get('notes')||''),next_step:String(f.get('next_step')||'')});setMsg('Mentoring session recorded.');setSessionPair('')}catch(err:any){setMsg(err.message)}}
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>Succession & mentoring</span><h1 style={{marginTop:14}}>Mentor–mentee development</h1><p>Pair experienced teachers with colleagues who can benefit from coaching and skill transfer.</p></div></div>{msg&&<div className="command"><div><b>{msg}</b></div><i className="pulse"/></div>}
 <div className="grid-2" style={{marginTop:18}}>{leadership&&<section className="panel"><h3>Create mentoring pair</h3><form className="form-grid" onSubmit={add}><div className="field full"><label>MENTOR</label><TeacherPicker name="mentor_teacher_id" required/></div><div className="field full"><label>MENTEE</label><TeacherPicker name="mentee_teacher_id" required/></div><div className="field full"><label>FOCUS AREA</label><input name="focus_area" required/></div><div className="field"><label>START DATE</label><input name="start_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><button className="btn btn-primary full">Create pair</button></form></section>}<section className="panel"><h3>Suggested mentors</h3><p style={{color:'var(--muted)'}}>Based on experience and current transparent performance score; leadership makes the final decision.</p>{suggestions.map((t:any)=><div className="metric" key={t.id}><span>{t.name} · {t.subject}</span><b>{t.experience}y</b></div>)}</section></div>
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h3>Mentoring pairs & session records</h3><p>Open a pair to record coaching objectives, notes and next steps.</p></div></div>{pairs.map((p:any)=><div className="queue-row" key={p.id}><div><b>{teachers.find((t:any)=>String(t.id)===String(p.mentor_teacher_id))?.name} → {teachers.find((t:any)=>String(t.id)===String(p.mentee_teacher_id))?.name}</b><small>{p.focus_area} · {p.status}</small></div><div className="toolbar"><span>{p.start_date}</span><button className="btn" onClick={()=>setSessionPair(String(p.id))}>Add session</button></div></div>)}{!pairs.length&&<div className="empty">No mentoring pairs yet.</div>}</section>
 {sessionPair&&<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setSessionPair('')}}><div className="modal modal-form" role="dialog" aria-modal="true"><div className="panel-head"><div><small>MENTORING RECORD</small><h2>New mentoring session</h2></div><button className="btn" onClick={()=>setSessionPair('')}>Close</button></div><form className="form-grid" onSubmit={addSession}><input type="hidden" name="pair_id" value={sessionPair}/><div className="field"><label>SESSION DATE</label><input name="session_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field full"><label>OBJECTIVE</label><input name="objective" required/></div><div className="field full"><label>NOTES</label><textarea name="notes"/></div><div className="field full"><label>NEXT STEP</label><input name="next_step"/></div><button className="btn btn-primary full">Record session</button></form></div></div>}
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h3>Recent mentoring sessions</h3><p>Professional coaching history</p></div></div>{[...sessions].sort((a:any,b:any)=>String(b.session_date).localeCompare(String(a.session_date))).slice(0,30).map((s:any)=><div className="queue-row" key={s.id}><div><b>{s.objective}</b><small>{s.session_date} · {s.notes||'No notes'}{s.next_step?` · Next: ${s.next_step}`:''}</small></div><span>Session</span></div>)}{!sessions.length&&<div className="empty">No mentoring sessions recorded.</div>}</section></>
}