'use client'
import { useEffect,useMemo,useRef,useState } from 'react'
import { Columns3,Download,Plus,X } from 'lucide-react'
import { useData } from './DataProvider'
import { TeacherPicker } from './TeacherPicker'

type Field={name:string;label:string;type?:string;options?:string[];required?:boolean;full?:boolean;defaultValue?:string|number}
type Props={title:string;subtitle:string;table:string;columns:{key:string;label:string;render?:(row:any)=>React.ReactNode}[];fields?:Field[];adminOnlyCreate?:boolean;createLabel?:string;transform?:(fd:FormData)=>Record<string,any>}

export function Page({title,subtitle,table,columns,fields=[],adminOnlyCreate=false,createLabel='Add record',transform}:Props){
 const{loading,data,insert,role}=useData()
 const[query,setQuery]=useState(''),[open,setOpen]=useState(false),[error,setError]=useState(''),[sort,setSort]=useState<{key:string;dir:1|-1}|null>(null),[last,setLast]=useState<Record<string,any>|null>(null)
 const[hidden,setHidden]=useState<string[]>([]),[limit,setLimit]=useState(25),[savedViews,setSavedViews]=useState<{name:string;query:string}[]>([]),[selected,setSelected]=useState<number[]>([]),[progress,setProgress]=useState(0),[hasDraft,setHasDraft]=useState(false)
 const formRef=useRef<HTMLFormElement>(null),rows=data[table]||[],canCreate=fields.length>0&&(!adminOnlyCreate||['principal','vice_principal'].includes(role)),draftKey=`tt-draft-${table}`
 useEffect(()=>{try{setQuery(localStorage.getItem(`tt-filter-${table}`)||'');setHidden(JSON.parse(localStorage.getItem(`tt-columns-${table}`)||'[]'));setSavedViews(JSON.parse(localStorage.getItem(`tt-views-${table}`)||'[]'));setHasDraft(Boolean(localStorage.getItem(draftKey)))}catch{}},[table,draftKey])
 useEffect(()=>{localStorage.setItem(`tt-filter-${table}`,query);setLimit(25)},[query,table])
 const visibleColumns=columns.filter(c=>!hidden.includes(c.key))
 const filtered=useMemo(()=>{const out=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));if(!sort)return out;return [...out].sort((a:any,b:any)=>String(a[sort.key]??'').localeCompare(String(b[sort.key]??''),undefined,{numeric:true})*sort.dir)},[rows,query,sort])
 const visible=filtered.slice(0,limit)
 function toggleSort(key:string){setSort(s=>s?.key===key?{key,dir:s.dir===1?-1:1}:{key,dir:1})}
 function toggleColumn(key:string){const next=hidden.includes(key)?hidden.filter(x=>x!==key):[...hidden,key];setHidden(next);localStorage.setItem(`tt-columns-${table}`,JSON.stringify(next))}
 function saveView(){if(!query.trim())return;const name=window.prompt('Name this saved view:',query.trim());if(!name)return;const next=[...savedViews.filter(v=>v.name!==name),{name,query}];setSavedViews(next);localStorage.setItem(`tt-views-${table}`,JSON.stringify(next))}
 function exportCsv(target=filtered){const clean=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=[visibleColumns.map(c=>clean(c.label)).join(','),...target.map(r=>visibleColumns.map(c=>clean(r[c.key])).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${table}.csv`;a.click();URL.revokeObjectURL(url)}
 function updateProgress(form:HTMLFormElement){const required=fields.filter(f=>f.required);if(!required.length)return setProgress(100);const fd=new FormData(form);setProgress(Math.round(required.filter(f=>String(fd.get(f.name)||'').trim()).length/required.length*100))}
 function saveDraft(form:HTMLFormElement){localStorage.setItem(draftKey,JSON.stringify({payload:Object.fromEntries(new FormData(form).entries()),savedAt:new Date().toISOString(),href:location.pathname,label:title}));setHasDraft(true)}
 function restoreDraft(){const form=formRef.current;if(!form)return;try{const d=JSON.parse(localStorage.getItem(draftKey)||'null');if(!d?.payload)return;for(const[k,v]of Object.entries(d.payload)){const el=form.elements.namedItem(k) as HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement|null;if(el&&el.type!=='hidden')el.value=String(v??'')}updateProgress(form)}catch{}}
 function duplicateLikely(payload:any){const keys=fields.filter(f=>payload[f.name]!==undefined&&payload[f.name]!==''&&!['notes','description','reason'].includes(f.name)).slice(0,3).map(f=>f.name);return keys.length>=2&&rows.some((r:any)=>keys.every(k=>String(r[k]??'').trim().toLowerCase()===String(payload[k]??'').trim().toLowerCase()))}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const submitter=(e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null,again=submitter?.value==='again',fd=new FormData(e.currentTarget),raw=Object.fromEntries(fd.entries()),payload=transform?transform(fd):raw;if(duplicateLikely(payload)&&!window.confirm('A similar record already exists. Save this possible duplicate anyway?'))return;if(!navigator.onLine){saveDraft(e.currentTarget);setError('Offline: draft saved locally and can be resumed later.');return}try{await insert(table,payload);localStorage.removeItem(draftKey);setHasDraft(false);setLast(raw);if(again){e.currentTarget.reset();setProgress(0)}else setOpen(false)}catch(err:any){saveDraft(e.currentTarget);setError((err.message||'Could not save')+' · Draft kept locally.')}}
 const defaultFor=(f:Field)=>last?.[f.name]??f.defaultValue??(f.type==='date'?new Date().toISOString().slice(0,10):undefined)
 function suggestions(f:Field){return [...new Set(rows.map((r:any)=>String(r[f.name]??'').trim()).filter(Boolean))].slice(0,20)}
 function displayCell(r:any,c:{key:string;label:string;render?:(row:any)=>React.ReactNode}){
  if(c.render)return c.render(r)
  const value=r[c.key]
  if(c.key.toLowerCase().includes('teacher_id')&&value!=null){const t=(data.teachers_dashboard||[]).find((x:any)=>String(x.id)===String(value));return t?<button className="teacher-cell-button" onClick={()=>window.dispatchEvent(new CustomEvent('tt-teacher-quick',{detail:{teacherId:t.id}}))}>{t.teacher_code||`ID ${t.id}`} · {t.name}</button>:`Teacher ID ${value}`}
  return String(value??'—')
 }
 if(loading)return <div className="loading">Loading secure school data…</div>
 return <>
  <div className="page-head"><div><span className="eyebrow"><i className="dot"/>TeachTrack module</span><h1>{title}</h1><p>{subtitle}</p></div><div className="toolbar global-search"><input className="search" placeholder="Search records…" value={query} onChange={e=>setQuery(e.target.value)}/>{savedViews.length>0&&<select className="compact-select" defaultValue="" onChange={e=>e.target.value&&setQuery(e.target.value)}><option value="">Saved views</option>{savedViews.map(v=><option key={v.name} value={v.query}>{v.name}</option>)}</select>}<button className="btn" onClick={saveView} disabled={!query.trim()}>Save view</button><details className="column-menu"><summary className="btn"><Columns3 size={15}/> Columns</summary><div className="column-menu-pop">{columns.map(c=><label key={c.key}><input type="checkbox" checked={!hidden.includes(c.key)} onChange={()=>toggleColumn(c.key)}/>{c.label}</label>)}</div></details><button className="btn" onClick={()=>exportCsv(selected.length?rows.filter((r:any)=>selected.includes(Number(r.id))):filtered)} disabled={!filtered.length}><Download size={15}/> {selected.length?`Export ${selected.length}`:'Export'}</button>{canCreate&&<button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={16}/> {createLabel}</button>}</div></div>
  {query&&<div className="filter-chips"><span>Search: {query}<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={12}/></button></span></div>}{selected.length>0&&<div className="bulk-bar"><b>{selected.length} selected</b><button className="btn" onClick={()=>setSelected([])}>Clear</button><button className="btn" onClick={()=>exportCsv(rows.filter((r:any)=>selected.includes(Number(r.id))))}>Export selected</button></div>}
  <section className="panel"><div className="panel-head"><div><h3>{title} records</h3><p>{filtered.length} matching item{filtered.length===1?'':'s'} · showing {visible.length}</p></div><span className="status good">Live database</span></div><div className="table-wrap responsive-table"><table className="table"><thead><tr><th><input type="checkbox" aria-label="Select visible records" checked={visible.length>0&&visible.every((r:any)=>selected.includes(Number(r.id)))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map((r:any)=>Number(r.id))])]:selected.filter(id=>!visible.some((r:any)=>Number(r.id)===id)))}/></th>{visibleColumns.map(c=><th key={c.key}><button className="sort-head" onClick={()=>toggleSort(c.key)}>{c.label}{sort?.key===c.key?(sort.dir===1?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{visible.map((r:any)=><tr key={r.id}><td data-label="Select"><input type="checkbox" checked={selected.includes(Number(r.id))} onChange={e=>setSelected(s=>e.target.checked?[...s,Number(r.id)]:s.filter(x=>x!==Number(r.id)))}/></td>{visibleColumns.map(c=><td data-label={c.label} key={c.key}>{displayCell(r,c)}</td>)}</tr>)}</tbody></table>{!filtered.length&&<div className="empty">{query?'No records match your current search. Clear the filter or try a shorter term.':canCreate?`No ${title.toLowerCase()} records yet. Use “${createLabel}” to create the first one.`:'No records are available for your account.'}</div>}</div>{visible.length<filtered.length&&<div className="load-more"><button className="btn" onClick={()=>setLimit(x=>x+25)}>Load 25 more</button></div>}</section>
  {open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="modal modal-form" role="dialog" aria-modal="true" aria-labelledby={`${table}-form-title`}><div className="panel-head"><div><h2 id={`${table}-form-title`}>{createLabel}</h2><p>Smart defaults, local drafts and duplicate protection are enabled.</p></div><button className="btn" onClick={()=>setOpen(false)}>Close</button></div><div className="form-progress"><span style={{width:`${progress}%`}}/><small>{progress}% required fields complete</small></div><form ref={formRef} className="form-grid" onInput={e=>updateProgress(e.currentTarget)} onChange={e=>{updateProgress(e.currentTarget);saveDraft(e.currentTarget)}} onSubmit={submit}>{fields.map(f=><div className={`field ${f.full?'full':''}`} key={f.name}><label>{f.label}{f.required?' *':''}</label>{f.name.toLowerCase().includes('teacher_id')?<TeacherPicker name={f.name} required={f.required} defaultValue={defaultFor(f)}/>:f.options?<select name={f.name} required={f.required} defaultValue={String(defaultFor(f)??'')}><option value="">Select…</option>{f.options.map(o=><option key={o} value={o}>{o}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} required={f.required} defaultValue={defaultFor(f)}/>:<><input name={f.name} list={`suggest-${table}-${f.name}`} type={f.type||'text'} required={f.required} defaultValue={defaultFor(f)}/>{f.type!=='number'&&f.type!=='date'&&suggestions(f).length>0&&<datalist id={`suggest-${table}-${f.name}`}>{suggestions(f).map(x=><option key={x} value={x}/>)}</datalist>}</>}</div>)}{error&&<div className="error full">{error}</div>}<div className="toolbar full"><button className="btn" type="button" onClick={()=>formRef.current&&saveDraft(formRef.current)}>Save draft</button>{hasDraft&&<button className="btn" type="button" onClick={restoreDraft}>Restore draft</button>}<button className="btn" type="submit" value="again">Save & add another</button><button className="btn btn-primary" type="submit">Save</button></div></form></div></div>}
 </>
}
export const status=(v:string)=><span className={`status ${['Present','Completed','Approved','Active'].includes(v)?'good':''}`}>{v}</span>
