'use client'
import { FormEvent,useState } from 'react'
import { useData } from '@/components/DataProvider'
import { TeacherPicker } from '@/components/TeacherPicker'
export default function SchoolGoals(){
 const{data,loading,role,insert,update}=useData();const[msg,setMsg]=useState('');const leadership=['principal','vice_principal','section_head'].includes(role);if(loading)return <div className="loading">Loading school goals…</div>
 const rows=data.school_goals||[]
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await insert('school_goals',{title:String(f.get('title')),category:String(f.get('category')),description:String(f.get('description')||''),target_value:Number(f.get('target_value')||100),current_value:Number(f.get('current_value')||0),unit:String(f.get('unit')||'%'),due_date:String(f.get('due_date')||'')||null,owner_teacher_id:f.get('owner_teacher_id')?Number(f.get('owner_teacher_id')):null,status:'Active'});setMsg('School improvement goal created.')}catch(err:any){setMsg(err.message)}}
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>School improvement</span><h1 style={{marginTop:14}}>School goals</h1><p>Connect teacher development activity to measurable school-wide priorities.</p></div></div>{msg&&<div className="command"><div><b>{msg}</b></div><i className="pulse"/></div>}
 {leadership&&<section className="panel" style={{marginTop:18}}><form className="form-grid" onSubmit={add}><div className="field"><label>TITLE</label><input name="title" required/></div><div className="field"><label>CATEGORY</label><input name="category" defaultValue="School Improvement"/></div><div className="field full"><label>DESCRIPTION</label><textarea name="description"/></div><div className="field"><label>CURRENT</label><input name="current_value" type="number" defaultValue="0"/></div><div className="field"><label>TARGET</label><input name="target_value" type="number" defaultValue="100"/></div><div className="field"><label>UNIT</label><input name="unit" defaultValue="%"/></div><div className="field"><label>DUE DATE</label><input name="due_date" type="date"/></div><div className="field full"><label>OWNER (OPTIONAL)</label><TeacherPicker name="owner_teacher_id"/></div><button className="btn btn-primary full">Create school goal</button></form></section>}
 <div className="cards" style={{marginTop:18}}>{rows.map((g:any)=><article className="person-card" key={g.id}><h3>{g.title}</h3><p>{g.description}</p><div className="metric"><span>Progress</span><b>{g.current_value}/{g.target_value}{g.unit}</b></div><div className="progress"><span style={{width:`${Math.min(100,Number(g.current_value||0)/Math.max(1,Number(g.target_value||100))*100)}%`}}/></div>{leadership&&<button className="btn" onClick={()=>update('school_goals',g.id,{status:g.status==='Completed'?'Active':'Completed'})}>{g.status==='Completed'?'Reopen':'Mark completed'}</button>}</article>)}</div></>
}