'use client'
import Link from 'next/link'
import { useState } from 'react'
import { Bell,CheckCheck,Plus,Settings } from 'lucide-react'
import { useData } from '@/components/DataProvider'
import { derivedAlerts } from '@/lib/teacherInsights'
export default function Notifications(){
 const{data,loading,role,profile,insert}=useData();const[open,setOpen]=useState(false),[msg,setMsg]=useState('');const leadership=['principal','vice_principal'].includes(role)
 const pref=(data.notification_preferences||[])[0]||{}
 const allowed=(n:any)=>{if(n.priority==='High')return true;const c=String(n.category||'General').toLowerCase();const k=c.includes('train')?'training':c.includes('observ')?'observations':c.includes('goal')?'goals':c.includes('timetable')||c.includes('substitut')?'timetable':c.includes('achiev')?'achievements':'general';return pref[k]!==false}
 const rows=[...(data.notifications||[])].filter(allowed).sort((a:any,b:any)=>String(b.created_at).localeCompare(String(a.created_at))),smart=derivedAlerts(data),teachers=data.teachers_dashboard||[]
 const readIds=new Set((data.notification_reads||[]).filter((r:any)=>r.user_id===profile?.id).map((r:any)=>String(r.notification_id)))
 const teacherName=(id:any)=>teachers.find((t:any)=>String(t.id)===String(id))?.name||''
 async function send(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{await insert('notifications',{recipient_user_id:null,title:String(fd.get('title')),message:String(fd.get('message')),category:String(fd.get('category')),priority:String(fd.get('priority')),action_url:String(fd.get('action_url')||'')||null});setOpen(false);setMsg('Notification sent to all staff.')}catch(err:any){setMsg(err.message)}}
 async function read(id:number){if(readIds.has(String(id)))return;try{await insert('notification_reads',{notification_id:id,user_id:profile?.id,read_at:new Date().toISOString()})}catch(err:any){setMsg(err.message)}}
 if(loading)return <div className="loading">Loading notifications…</div>
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>Notification centre</span><h1 style={{marginTop:14}}>Notifications</h1><p>Individual read state, smart reminders and school-wide announcements.</p></div><div className="toolbar"><Link className="btn" href="/notification-preferences"><Settings size={15}/> Preferences</Link>{leadership&&<button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={16}/> Send announcement</button>}</div></div>
 {msg&&<div className="command" style={{marginBottom:18}}><div><small>STATUS</small><b>{msg}</b></div><i className="pulse"/></div>}
 <section className="panel" style={{marginBottom:18}}><div className="panel-head"><div><h3>Smart attention feed</h3><p>Automatically derived from deadlines, follow-ups and pending workflows.</p></div><span className="status">{smart.length} active</span></div><div className="cms-queue">{smart.map((a:any,i:number)=><div className="queue-row" key={`${a.kind}-${i}`}><div><b>{a.title}</b><small>{a.detail}{a.teacher_id?` · ${teacherName(a.teacher_id)||`Teacher ID ${a.teacher_id}`}`:''}</small></div><span className={a.priority==='High'?'priority-high':'priority-normal'}>{a.kind}</span></div>)}</div>{!smart.length&&<div className="empty">No automatic attention items right now.</div>}</section>
 <section className="panel"><div className="cms-queue">{rows.map((n:any)=>{const isRead=readIds.has(String(n.id));return <div className={`queue-row ${!isRead?'notice-unread':''}`} key={n.id}><div><b><Bell size={13} style={{verticalAlign:'middle',marginRight:7}}/>{n.title}</b><small>{n.message}</small><small>{new Date(n.created_at).toLocaleString('en-GB',{timeZone:'Asia/Colombo'})} · {n.category}</small></div><div className="toolbar"><span className={n.priority==='High'?'priority-high':'priority-normal'}>{n.priority}</span>{!isRead&&<button className="btn" onClick={()=>read(n.id)}><CheckCheck size={14}/> Mark read</button>}{n.action_url&&<Link className="btn" href={n.action_url}>Open</Link>}</div></div>})}</div>{!rows.length&&<div className="empty">You're all caught up.</div>}</section>
 {open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><div className="modal modal-form" role="dialog" aria-modal="true"><div className="panel-head"><div><small>ALL STAFF</small><h2>Send announcement</h2></div><button className="btn" onClick={()=>setOpen(false)}>Close</button></div><form onSubmit={send} className="form-grid"><div className="field full"><label>TITLE</label><input name="title" required/></div><div className="field"><label>CATEGORY</label><select name="category"><option>General</option><option>Timetable</option><option>Training</option><option>Observation</option><option>Exam</option></select></div><div className="field"><label>PRIORITY</label><select name="priority"><option>Normal</option><option>High</option></select></div><div className="field full"><label>MESSAGE</label><textarea name="message" rows={5} required/></div><div className="field full"><label>ACTION URL (OPTIONAL)</label><input name="action_url" placeholder="/timetable"/></div><button className="btn btn-primary full">Send to all staff</button></form></div></div>}
 </>}
