'use client'
import { useState } from 'react'
import { Printer,FileText } from 'lucide-react'
import { useData } from '@/components/DataProvider'
export default function Reports(){
 const {data,loading,profile,role}=useData();const teachers=data.teachers_dashboard||[];const[selected,setSelected]=useState('');const leadership=['principal','vice_principal','section_head','reviewer'].includes(role);if(loading)return <div className="loading">Preparing reports…</div>
 const t=teachers.find((x:any)=>String(x.id)===selected)||teachers.find((x:any)=>String(x.id)===String(profile?.teacher_id))||teachers[0];if(!t)return <div className="panel empty">Add teachers before generating reports.</div>
 const pick=(name:string)=>(data[name]||[]).filter((x:any)=>String(x.teacher_id)===String(t.id))
 const attendance=pick('attendance'),training=pick('training'),feedback=pick('feedback'),lessons=pick('lessons'),obs=pick('observations'),ach=pick('achievements'),goals=pick('goals'),service=pick('teacher_service_history')
 const rating=feedback.length?(feedback.reduce((s:number,x:any)=>s+Number(x.rating||0),0)/feedback.length).toFixed(1):'—'
 return <><div className="page-head no-print"><div><span className="eyebrow"><i className="dot"/>Reports & teacher portfolio</span><h1 style={{marginTop:14}}>Printable professional portfolio</h1><p>Generate a competition-ready teacher summary using live school records.</p></div><div className="toolbar">{leadership&&<select className="search" value={String(t.id)} onChange={e=>setSelected(e.target.value)}>{teachers.map((x:any)=><option key={x.id} value={x.id}>{x.teacher_code?`${x.teacher_code} · `:''}{x.name}</option>)}</select>}<button className="btn btn-primary" onClick={()=>window.print()}><Printer size={16}/> Print / Save PDF</button></div></div>
 <div className="print-only"><h1>TeachTrack Teacher Portfolio</h1><p>Generated {new Date().toLocaleDateString('en-GB',{timeZone:'Asia/Colombo'})}</p></div>
 <section className="panel"><div className="panel-head"><div><small>TEACHER PROFILE</small><h2>{t.name}</h2><p><b>{t.teacher_code||`TCH-${String(t.id).padStart(4,'0')}`}</b> · {t.subject||'Teacher'} · {t.email||''}</p></div><FileText size={28}/></div><div className="kpis"><div className="kpi"><small>PERFORMANCE</small><b>{t.performance_score||0}%</b><span>Current score</span></div><div className="kpi"><small>FEEDBACK</small><b>{rating}</b><span>Average rating</span></div><div className="kpi"><small>TRAINING</small><b>{training.length}</b><span>Development records</span></div><div className="kpi"><small>ACHIEVEMENTS</small><b>{ach.length}</b><span>Recognitions</span></div></div></section>
 <div className="grid-2" style={{marginTop:18}}><section className="panel"><h3>Professional development</h3>{training.slice(0,10).map((x:any)=><div className="metric" key={x.id}><span>{x.title}</span><b>{x.provider}</b></div>)}{!training.length&&<p className="empty">No training records.</p>}</section><section className="panel"><h3>Classroom observation</h3>{obs.slice(0,10).map((x:any)=><div className="metric" key={x.id}><span>{x.focus_area}</span><b>★ {x.rating}</b></div>)}{!obs.length&&<p className="empty">No observations.</p>}</section></div>
 <div className="grid-2" style={{marginTop:18}}><section className="panel"><h3>Career milestones</h3><div className="timeline">{service.map((x:any)=><div className="timeline-item" key={x.id}><b>{x.title}</b><small>{x.event_type} · {x.effective_date}</small></div>)}</div></section><section className="panel"><h3>Achievements & goals</h3>{ach.map((x:any)=><div className="metric" key={x.id}><span>{x.title}</span><b>Achievement</b></div>)}{goals.map((x:any)=><div className="metric" key={x.id}><span>{x.title}</span><b>{x.status}</b></div>)}</section></div>
 <section className="panel" style={{marginTop:18}}><h3>Attendance summary</h3><div className="kpis" style={{gridTemplateColumns:'repeat(3,1fr)'}}><div className="kpi"><small>PRESENT</small><b>{attendance.filter((x:any)=>x.status==='Present').length}</b><span>records</span></div><div className="kpi"><small>LATE</small><b>{attendance.filter((x:any)=>x.status==='Late').length}</b><span>records</span></div><div className="kpi"><small>ABSENT</small><b>{attendance.filter((x:any)=>x.status==='Absent').length}</b><span>records</span></div></div></section></>
}
