'use client'
import { useMemo,useState } from 'react'
import { WandSparkles,Plus,Trash2,Save,AlertTriangle } from 'lucide-react'
import { useData } from '@/components/DataProvider'
import { TeacherPicker } from '@/components/TeacherPicker'
import { createClient } from '@/lib/supabase/client'

type Row=Record<string,any>
const DAYS=[{id:1,label:'Monday'},{id:2,label:'Tuesday'},{id:3,label:'Wednesday'},{id:4,label:'Thursday'},{id:5,label:'Friday'}]

export default function TimetableGenerator(){
 const {data,loading,role,insert,remove,refresh}=useData()
 const leadership=['principal','vice_principal'].includes(role)
 const classes=data.timetable_classes||[],teachers=data.teachers_dashboard||[],periods=(data.school_periods||[]).filter((p:any)=>!p.is_interval),reqs=data.class_subject_requirements||[],existing=data.timetable_entries||[]
 const[selectedClass,setSelectedClass]=useState(String(classes[0]?.id||''));const[preview,setPreview]=useState<Row[]>([]);const[unscheduled,setUnscheduled]=useState<Row[]>([]);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false)
 const selected=classes.find((c:any)=>String(c.id)===selectedClass)
 const classReqs=reqs.filter((r:any)=>String(r.class_id)===selectedClass)
 const teacher=(id:any)=>teachers.find((t:any)=>String(t.id)===String(id))
 const period=(id:any)=>periods.find((p:any)=>Number(p.id)===Number(id))

 async function addRequirement(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();const f=new FormData(e.currentTarget);try{await insert('class_subject_requirements',{class_id:Number(selectedClass),teacher_id:Number(f.get('teacher_id')),subject:String(f.get('subject')),periods_per_week:Number(f.get('periods_per_week')),room:String(f.get('room')||selected?.room||''),priority:Number(f.get('priority')||1)});setMsg('Subject requirement saved.')}catch(e:any){setMsg(e.message)}
 }

 function generate(){
  if(!selected){setMsg('Select a class first.');return}
  const generated:Row[]=[];const failed:Row[]=[]
  const existingForClass=existing.filter((e:any)=>String(e.class_id)===selectedClass)
  const occupiedClass=new Set(existingForClass.map((e:any)=>`${e.day_of_week}:${e.period_id}`))
  const occupiedTeacher=new Set(existing.map((e:any)=>`${e.teacher_id}:${e.day_of_week}:${e.period_id}`))
  const occupiedRoom=new Set(existing.filter((e:any)=>String(e.room||'').trim()).map((e:any)=>`${String(e.room).trim().toLowerCase()}:${e.day_of_week}:${e.period_id}`))
  const teacherLoad:Record<string,number>={}
  existing.forEach((e:any)=>teacherLoad[e.teacher_id]=(teacherLoad[e.teacher_id]||0)+1)

  const ordered=[...classReqs].sort((a:any,b:any)=>Number(b.priority)-Number(a.priority)||Number(b.periods_per_week)-Number(a.periods_per_week))
  for(const r of ordered){
   const already=existingForClass.filter((e:any)=>String(e.subject).toLowerCase()===String(r.subject).toLowerCase()).length
   const needed=Math.max(0,Number(r.periods_per_week)-already)
   for(let n=0;n<needed;n++){
    const candidates:Dual[] = []
    for(const day of DAYS)for(const p of periods){
     const classKey=`${day.id}:${p.id}`, teacherKey=`${r.teacher_id}:${day.id}:${p.id}`, roomKey=`${String(r.room||'').trim().toLowerCase()}:${day.id}:${p.id}`
     if(occupiedClass.has(classKey)||occupiedTeacher.has(teacherKey)||(r.room&&occupiedRoom.has(roomKey)))continue
     const sameSubjectDay=generated.filter(g=>g.day_of_week===day.id&&String(g.subject).toLowerCase()===String(r.subject).toLowerCase()).length
     const classDayLoad=[...existingForClass,...generated].filter(g=>Number(g.day_of_week)===day.id).length
     const teacherDayLoad=[...existing,...generated].filter(g=>String(g.teacher_id)===String(r.teacher_id)&&Number(g.day_of_week)===day.id).length
     const adjacent=generated.some(g=>g.day_of_week===day.id&&String(g.subject).toLowerCase()===String(r.subject).toLowerCase()&&Math.abs(Number(g.period_id)-Number(p.id))===1)
     const score=sameSubjectDay*30+classDayLoad*4+teacherDayLoad*8+(teacherLoad[r.teacher_id]||0)*2+(adjacent?12:0)+Math.random()*2
     candidates.push({day:day.id,period:Number(p.id),score})
    }
    candidates.sort((a,b)=>a.score-b.score)
    const best=candidates[0]
    if(!best){failed.push({...r,remaining:needed-n});break}
    const row={class_id:Number(selectedClass),teacher_id:Number(r.teacher_id),day_of_week:best.day,period_id:best.period,subject:r.subject,room:r.room||selected.room||'',notes:'Generated by TeachTrack timetable engine'}
    generated.push(row);occupiedClass.add(`${best.day}:${best.period}`);occupiedTeacher.add(`${r.teacher_id}:${best.day}:${best.period}`);if(row.room)occupiedRoom.add(`${String(row.room).trim().toLowerCase()}:${best.day}:${best.period}`);teacherLoad[r.teacher_id]=(teacherLoad[r.teacher_id]||0)+1
   }
  }
  setPreview(generated);setUnscheduled(failed);setMsg(failed.length?`Generated ${generated.length} lessons with ${failed.length} unresolved requirement(s).`:`Generated ${generated.length} lessons with no clashes.`)
 }

 async function commit(){
  if(!preview.length)return setMsg('Generate a timetable preview first.')
  setBusy(true);const supabase=createClient();const r=await supabase.from('timetable_entries').insert(preview)
  if(r.error)setMsg(r.error.message);else{setMsg(`${preview.length} generated lessons saved to the live timetable.`);setPreview([]);setUnscheduled([]);await refresh()}
  setBusy(false)
 }

 if(loading)return <div className="loading">Preparing timetable generator…</div>
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>Constraint-based scheduling</span><h1 style={{marginTop:14}}>Generate class timetable</h1><p>Define weekly subject requirements, then automatically distribute lessons while avoiding class, teacher and room clashes.</p></div>{leadership&&<div className="toolbar"><button className="btn" onClick={generate}><WandSparkles size={16}/> Generate preview</button><button className="btn btn-primary" disabled={!preview.length||busy} onClick={commit}><Save size={16}/> {busy?'Saving…':'Save timetable'}</button></div>}</div>
 {msg&&<div className="command" style={{marginBottom:18}}><div><small>GENERATOR STATUS</small><b>{msg}</b></div><i className="pulse"/></div>}
 <div className="grid-2"><section className="panel"><div className="panel-head"><div><h2>Class requirements</h2><p>Periods per week and assigned subject teachers.</p></div><select className="search" value={selectedClass} onChange={e=>{setSelectedClass(e.target.value);setPreview([])}}>{classes.map((c:any)=><option key={c.id} value={c.id}>{c.name} · {c.grade} · {c.academic_year||new Date().getFullYear()}</option>)}</select></div>
 {leadership&&selected&&<form onSubmit={addRequirement} className="form-grid"><div className="field"><label>SUBJECT</label><input name="subject" required/></div><div className="field"><label>TEACHER</label><TeacherPicker name="teacher_id" required={true} allowEmpty={false} placeholder="Search teacher code, ID or name…"/></div><div className="field"><label>PERIODS / WEEK</label><input name="periods_per_week" type="number" min="1" max="20" defaultValue="5" required/></div><div className="field"><label>ROOM</label><input name="room" defaultValue={selected.room||''}/></div><div className="field"><label>PRIORITY 1–5</label><input name="priority" type="number" min="1" max="5" defaultValue="1"/></div><div className="field" style={{justifyContent:'end'}}><button className="btn btn-primary"><Plus size={15}/> Add requirement</button></div></form>}
 <div className="table-wrap" style={{marginTop:16}}><table className="table"><thead><tr><th>Subject</th><th>Teacher</th><th>Periods</th><th>Room</th><th>Priority</th>{leadership&&<th/>}</tr></thead><tbody>{classReqs.map((r:any)=><tr key={r.id}><td>{r.subject}</td><td>{teacher(r.teacher_id)?.name||r.teacher_id}</td><td>{r.periods_per_week}</td><td>{r.room||'—'}</td><td>{r.priority}</td>{leadership&&<td><button className="btn" onClick={()=>remove('class_subject_requirements',r.id)}><Trash2 size={14}/></button></td>}</tr>)}</tbody></table>{!classReqs.length&&<div className="empty">Add subject requirements before generating.</div>}</div></section>
 <section className="panel"><div className="panel-head"><div><h2>Generation rules</h2><p>What the scheduler optimizes automatically.</p></div></div>{['No class can occupy two lessons at once','No teacher can teach two classes at once','Rooms cannot be double-booked','Interval is never scheduled','Subject lessons are spread across the week','Teacher and class daily load is balanced','Existing timetable entries are preserved'].map(x=><div className="metric" key={x}><span>{x}</span><b>✓</b></div>)}</section></div>
 {preview.length>0&&<section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Generated preview</h2><p>{preview.length} new lesson(s) ready to save.</p></div>{unscheduled.length>0&&<span className="status"><AlertTriangle size={13}/> {unscheduled.length} unresolved</span>}</div><div className="table-wrap"><table className="table"><thead><tr><th>Day</th><th>Period</th><th>Subject</th><th>Teacher</th><th>Room</th></tr></thead><tbody>{preview.sort((a,b)=>a.day_of_week-b.day_of_week||a.period_id-b.period_id).map((r:any,i)=><tr key={i}><td>{DAYS.find(d=>d.id===r.day_of_week)?.label}</td><td>{period(r.period_id)?.label}</td><td>{r.subject}</td><td>{teacher(r.teacher_id)?.name}</td><td>{r.room||'—'}</td></tr>)}</tbody></table></div>{unscheduled.map((u:any,i)=><div className="command" key={i} style={{marginTop:10}}><div><small>UNRESOLVED</small><b>{u.subject}: unable to place {u.remaining} period(s) without a clash.</b></div><AlertTriangle size={18}/></div>)}</section>}
 </>}
type Dual={day:number;period:number;score:number}
