'use client'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { useData } from '@/components/DataProvider'
import { derivedAlerts, performanceTrend } from '@/lib/teacherInsights'
import { OnboardingChecklist } from '@/components/OnboardingChecklist'
import { DashboardWidgetBoard } from '@/components/DashboardWidgetBoard'
function Kpi({label,value,note}:{label:string,value:string|number,note:string}){return <div className="kpi"><small>{label}</small><b>{value}</b><span>{note}</span></div>}
export default function Dashboard(){
 const{loading,data,profile,role}=useData();const[prefs,setPrefs]=useState({calendar:true,quick:true,activity:true})
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('tt-dashboard')||'{}');setPrefs(v=>({...v,...p}))}catch{}},[]);if(loading)return <div className="loading">Preparing your command center…</div>
 const leadership=['principal','vice_principal'].includes(role)
 const teachers=data.teachers_dashboard||[],attendance=data.attendance||[],training=data.training||[],feedback=data.feedback||[],lessons=data.lessons||[],goals=data.goals||[],obs=data.observations||[]
 const leaves=data.leave_requests||[],events=data.school_events||[],entries=data.timetable_entries||[],notifications=data.notifications||[],docs=data.teacher_documents||[]
 const myTeacherId=String(profile?.teacher_id||'')
 const mine=(rows:any[])=>leadership?rows:rows.filter((x:any)=>String(x.teacher_id)===myTeacherId)
 const scopedTeachers=leadership?teachers:teachers.filter((t:any)=>String(t.id)===myTeacherId)
 const scopedAttendance=mine(attendance),scopedTraining=mine(training),scopedFeedback=mine(feedback),scopedLessons=mine(lessons),scopedGoals=mine(goals),scopedObs=mine(obs),scopedEntries=mine(entries)
 const today=new Date().toISOString().slice(0,10)
 const onLeave=leaves.filter((l:any)=>l.status==='Approved'&&l.start_date<=today&&l.end_date>=today).length
 const pendingLeave=leaves.filter((l:any)=>l.status==='Pending').length
 const upcomingEvents=events.filter((e:any)=>String(e.start_at).slice(0,10)>=today).sort((a:any,b:any)=>String(a.start_at).localeCompare(String(b.start_at))).slice(0,4)
 const expiringDocs=docs.filter((d:any)=>d.expiry_date&&d.expiry_date>=today&&d.expiry_date<=new Date(Date.now()+30*86400000).toISOString().slice(0,10)).length
 const avgPerf=scopedTeachers.length?Math.round(scopedTeachers.reduce((s:number,t:any)=>s+Number(t.performance_score||0),0)/scopedTeachers.length):0
 const avgFeedback=scopedFeedback.length?(scopedFeedback.reduce((s:number,f:any)=>s+Number(f.rating),0)/scopedFeedback.length).toFixed(1):'0.0'
 const late=scopedAttendance.filter((a:any)=>a.status==='Late').length,activeGoals=scopedGoals.filter((g:any)=>g.status==='Active').length
 const recent=[...data.activity_logs||[]].sort((a:any,b:any)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,6)
 const smartAlerts=derivedAlerts(data).slice(0,6)
 const declining=teachers.map((t:any)=>({t,trend:performanceTrend(data,t)})).filter((x:any)=>x.trend.direction==='Needs attention').sort((a:any,b:any)=>a.trend.delta-b.trend.delta).slice(0,5)
 const improving=teachers.map((t:any)=>({t,trend:performanceTrend(data,t)})).filter((x:any)=>x.trend.direction==='Improving').sort((a:any,b:any)=>b.trend.delta-a.trend.delta).slice(0,5)
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>{leadership?'School leadership command center':'Teacher development command center'}</span><h1>Good day, {profile?.full_name?.split(' ')[0]||'Teacher'}.</h1><p>{leadership?'Live school operations, staffing and teacher-development intelligence.':'Your teaching, development and recognition in one place.'}</p></div><Link className="btn btn-primary" href="/analytics">View analytics →</Link></div>
 {!leadership&&<OnboardingChecklist/>}
 <DashboardWidgetBoard/>
 <div className="kpis">{leadership?<><Kpi label="TEACHERS" value={teachers.length} note="Active faculty records"/><Kpi label="ON LEAVE TODAY" value={onLeave} note={`${pendingLeave} requests pending`}/><Kpi label="WEEKLY LESSONS" value={entries.length} note="Timetable assignments"/><Kpi label="AVG PERFORMANCE" value={`${avgPerf}%`} note="Composite development score"/></>:<><Kpi label="AVG PERFORMANCE" value={`${avgPerf}%`} note="Composite development score"/><Kpi label="FEEDBACK RATING" value={`${avgFeedback}/5`} note={`${scopedFeedback.length} feedback records`}/><Kpi label="ACTIVE GOALS" value={activeGoals} note="Professional growth targets"/><Kpi label="NOTIFICATIONS" value={notifications.filter((n:any)=>!n.read_at).length} note="Current alerts"/></>}</div>
 <div className="grid"><section className="panel"><div className="panel-head"><div><small style={{color:'#7c899c'}}>LIVE OPERATIONS</small><h2>{leadership?'Principal overview':"Today's activity"}</h2><p>Operational data from Supabase</p></div><span className="status">Live</span></div>
 <div className="kpis" style={{gridTemplateColumns:'repeat(3,1fr)'}}><Kpi label="LATE ARRIVALS" value={late} note="Attendance exceptions"/><Kpi label="TRAINING" value={scopedTraining.length} note="Development records"/><Kpi label="LESSON PLANS" value={scopedLessons.length} note="Planning records"/></div>
 <div className="command"><div><small>Platform status</small><b>All systems active · {expiringDocs} document(s) expiring soon</b></div><i className="pulse"/></div></section>
 <section className="panel"><div className="panel-head"><div><h3>Development signals</h3><p>Items worth attention</p></div></div>{[{l:'Pending leave',v:pendingLeave},{l:'Pending lessons',v:lessons.filter((x:any)=>x.status==='Pending').length},{l:'At-risk goals',v:goals.filter((x:any)=>x.status==='At Risk').length},{l:'Observation follow-ups',v:obs.filter((x:any)=>x.status==='Follow-up').length},{l:'Achievements',v:(data.achievements||[]).length}].map(x=><div className="metric" key={x.l}><span>{x.l}</span><b>{x.v}</b></div>)}</section></div>
 {(prefs.calendar||prefs.quick)&&<div className="grid-2" style={{marginTop:18}}>{prefs.calendar&&<section className="panel"><div className="panel-head"><div><h3>Upcoming school calendar</h3><p>Next scheduled events</p></div><Link href="/calendar" className="btn">Calendar →</Link></div>{upcomingEvents.map((e:any)=><div className="calendar-row" key={e.id}><div className="calendar-date">{new Date(e.start_at).toLocaleDateString('en-GB',{timeZone:'Asia/Colombo'})}</div><div><b>{e.title}</b><small style={{display:'block',color:'var(--muted)'}}>{e.event_type} · {e.location||'School'}</small></div><span className="status good">{e.audience}</span></div>)}{!upcomingEvents.length&&<div className="empty">No upcoming events.</div>}</section>}{prefs.quick&&<section className="panel"><div className="panel-head"><div><h3>Quick operations</h3><p>Common school workflows</p></div></div><div className="cms-actions">{leadership?<><Link className="cms-action" href="/leave"><b>Leave & substitute cover</b><span>Review absence and find free teachers →</span></Link><Link className="cms-action" href="/timetable"><b>Timetable</b><span>Classes, lessons and substitutions →</span></Link><Link className="cms-action" href="/workload"><b>Teacher workload</b><span>Compare weekly teaching allocations →</span></Link><Link className="cms-action" href="/notifications"><b>Notifications</b><span>Announcements and system alerts →</span></Link></>:<><Link className="cms-action" href="/my-hub"><b>My professional hub</b><span>Personal evidence and quick actions →</span></Link><Link className="cms-action" href="/timetable"><b>My timetable</b><span>View teaching schedule →</span></Link><Link className="cms-action" href="/goals"><b>My goals</b><span>Professional development targets →</span></Link><Link className="cms-action" href="/documents"><b>My documents</b><span>Qualifications and certificates →</span></Link></>}</div></section>}</div>}
 {leadership&&<div className="grid-2" style={{marginTop:18}}><section className="panel"><div className="panel-head"><div><h3>Needs attention</h3><p>Rule-based operational and development alerts</p></div><span className="status">{smartAlerts.length}</span></div>{smartAlerts.map((a:any,i:number)=><div className="queue-row" key={`${a.kind}-${i}`}><div><b>{a.title}</b><small>{a.kind} · {a.detail}</small></div><span className={`status ${a.priority==='High'?'':'good'}`}>{a.priority}</span></div>)}{!smartAlerts.length&&<div className="empty">No urgent attention items.</div>}</section><section className="panel"><div className="panel-head"><div><h3>Performance movement</h3><p>Recent evidence trend detection</p></div></div>{declining.map((x:any)=><div className="metric" key={`d-${x.t.id}`}><span>↓ {x.t.name}</span><b>{x.trend.delta}</b></div>)}{improving.map((x:any)=><div className="metric" key={`i-${x.t.id}`}><span>↑ {x.t.name}</span><b>+{x.trend.delta}</b></div>)}{!declining.length&&!improving.length&&<div className="empty">Performance is currently stable.</div>}</section></div>}
 {prefs.activity&&<section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h3>Recent activity</h3><p>Audit trail of important platform actions</p></div><span className="status good">Secure log</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Actor</th><th>Action</th><th>Module</th><th>Time</th></tr></thead><tbody>{recent.map((r:any)=><tr key={r.id}><td>{r.actor_name}</td><td>{r.action}</td><td>{r.entity_type}</td><td>{new Date(r.created_at).toLocaleString('en-GB',{timeZone:'Asia/Colombo'})}</td></tr>)}</tbody></table>{!recent.length&&<div className="empty">Activity will appear here as the school uses TeachTrack.</div>}</div></section>}</>
}
