'use client'
import { useMemo,useState } from 'react'
import { useData } from '@/components/DataProvider'
function clamp(v:number){return Math.max(0,Math.min(100,Math.round(v)))}
export default function Intelligence(){
 const {data,loading,profile,role}=useData();const teachers=data.teachers_dashboard||[];const[selected,setSelected]=useState('');const leadership=['principal','vice_principal','section_head','reviewer'].includes(role)
 const t=teachers.find((x:any)=>String(x.id)===selected)||teachers.find((x:any)=>String(x.id)===String(profile?.teacher_id))||teachers[0];if(loading)return <div className="loading">Building growth intelligence…</div>
 if(!t)return <div className="panel empty">Add a teacher profile to use Growth Intelligence.</div>
 const attendance=(data.attendance||[]).filter((x:any)=>String(x.teacher_id)===String(t.id)),feedback=(data.feedback||[]).filter((x:any)=>String(x.teacher_id)===String(t.id)),training=(data.training||[]).filter((x:any)=>String(x.teacher_id)===String(t.id)),lessons=(data.lessons||[]).filter((x:any)=>String(x.teacher_id)===String(t.id)),obs=(data.observations||[]).filter((x:any)=>String(x.teacher_id)===String(t.id)),ach=(data.achievements||[]).filter((x:any)=>String(x.teacher_id)===String(t.id)),goals=(data.goals||[]).filter((x:any)=>String(x.teacher_id)===String(t.id)),service=(data.teacher_service_history||[]).filter((x:any)=>String(x.teacher_id)===String(t.id))
 const present=attendance.filter((x:any)=>x.status==='Present').length,late=attendance.filter((x:any)=>x.status==='Late').length
 const att=attendance.length?clamp(((present+late)/attendance.length)*100):100,punct=attendance.length?clamp((present/attendance.length)*100):100
 const fb=feedback.length?clamp((feedback.reduce((s:number,x:any)=>s+Number(x.rating||0),0)/feedback.length)/5*100):80
 const ob=obs.length?clamp((obs.reduce((s:number,x:any)=>s+Number(x.rating||0),0)/obs.length)/5*100):80
 const lesson=lessons.length?clamp(lessons.filter((x:any)=>['Approved','Completed'].includes(x.status)).length/lessons.length*100):75
 const train=clamp(Math.min(100,training.length*12)),achievement=clamp(Math.min(100,ach.length*18))
 const score=clamp(att*.18+punct*.12+ob*.22+fb*.16+lesson*.14+train*.1+achievement*.08)
 const metrics=[['Attendance',att,18],['Punctuality',punct,12],['Observation',ob,22],['Feedback',fb,16],['Lesson planning',lesson,14],['Training',train,10],['Achievements',achievement,8]] as const
 const weakest=[...metrics].sort((a,b)=>a[1]-b[1])[0],strong=[...metrics].sort((a,b)=>b[1]-a[1]).slice(0,2)
 const timeline=[...service.map((x:any)=>({date:x.effective_date,title:x.title,type:x.event_type})),...training.map((x:any)=>({date:x.date||x.created_at,title:x.title,type:'Training'})),...ach.map((x:any)=>({date:x.date||x.created_at,title:x.title,type:'Achievement'}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,10)
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>Teacher growth intelligence</span><h1 style={{marginTop:14}}>Performance + 360° profile</h1><p>A transparent composite view of teaching performance, professional development and career milestones.</p></div>{leadership&&<select className="search" value={String(t.id)} onChange={e=>setSelected(e.target.value)}>{teachers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}</div>
 <div className="grid"><section className="panel"><div className="panel-head"><div><small>COMPOSITE SCORE</small><h2>{t.name}</h2><p>{t.subject||'Teacher'} · transparent weighted score</p></div><div className="hero-score">{score}</div></div>{metrics.map(m=><div key={m[0]} style={{marginTop:14}}><div className="metric"><span>{m[0]} · weight {m[2]}%</span><b>{m[1]}%</b></div><div className="progress"><span style={{width:`${m[1]}%`}}/></div></div>)}</section>
 <section className="panel"><div className="panel-head"><div><h3>Growth signals</h3><p>Explainable recommendations</p></div></div><div className="feature-card"><h3>Strengths</h3><p>{strong.map(x=>x[0]).join(' · ')}</p></div><div className="feature-card" style={{marginTop:10}}><h3>Development opportunity</h3><p>{weakest[0]} currently has the lowest component score at {weakest[1]}%.</p></div><div className="feature-card" style={{marginTop:10}}><h3>Recommended next step</h3><p>Assign a development plan focused on {String(weakest[0]).toLowerCase()} and review it at the next observation.</p></div></section></div>
 <div className="grid-2" style={{marginTop:18}}><section className="panel"><div className="panel-head"><div><h3>Career timeline</h3><p>Service, training and recognition</p></div></div><div className="timeline">{timeline.map((x:any,i)=><div className="timeline-item" key={i}><b>{x.title}</b><small>{x.type} · {String(x.date||'').slice(0,10)}</small></div>)}{!timeline.length&&<div className="empty">Career milestones will appear here.</div>}</div></section>
 <section className="panel"><div className="panel-head"><div><h3>Professional snapshot</h3><p>Current teacher-development records</p></div></div>{[['Training records',training.length],['Lesson plans',lessons.length],['Observations',obs.length],['Feedback records',feedback.length],['Goals',goals.length],['Achievements',ach.length]].map(x=><div className="metric" key={String(x[0])}><span>{x[0]}</span><b>{x[1]}</b></div>)}</section></div></>
}
