'use client'
import { useEffect,useMemo,useState } from 'react'
import { Download,Printer,Save } from 'lucide-react'
import { useData } from '@/components/DataProvider'
import { completeness,workloadScore } from '@/lib/advancedUx'
import { composite,performanceTrend } from '@/lib/teacherInsights'
export default function ReportBuilder(){
 const{data,loading,role,insert}=useData();const[dept,setDept]=useState('All'),[metric,setMetric]=useState('performance'),[name,setName]=useState(''),[msg,setMsg]=useState('');const presets=data.saved_report_presets||[]
 const teachers=data.teachers_dashboard||[],departments=['All',...new Set(teachers.map((t:any)=>t.department).filter(Boolean))]
 const rows=useMemo(()=>teachers.filter((t:any)=>dept==='All'||t.department===dept).map((t:any)=>{const c=composite(data,t),w=workloadScore(data,t.id),cp=completeness(data,t),trend=performanceTrend(data,t);return {teacher:t,performance:c.score,workload:w.total,completeness:cp.score,trend:trend.direction}}),[teachers,dept,data])
 if(loading)return <div className="loading">Building report…</div>
 if(!['principal','vice_principal','section_head','reviewer'].includes(role))return <div className="panel empty">Report Builder is available to school leadership and reviewers.</div>
 function csv(){const text=['Teacher,Department,Performance,Workload,Completeness,Trend',...rows.map((x:any)=>`"${x.teacher.name}","${x.teacher.department}",${x.performance},${x.workload},${x.completeness},"${x.trend}"`)].join('\n');const b=new Blob([text],{type:'text/csv'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='teachtrack-report.csv';a.click();URL.revokeObjectURL(u)}
 async function save(){if(!name.trim())return setMsg('Enter a preset name first.');try{await insert('saved_report_presets',{name,configuration:{department:dept,metric}});setMsg('Report preset saved.')}catch(err:any){setMsg(err.message)}}
 return <><div className="page-head no-print"><div><span className="eyebrow"><i className="dot"/>Report builder</span><h1 style={{marginTop:14}}>Custom management report</h1><p>Choose a department and evidence view, then print, export or save the preset.</p></div><div className="toolbar"><button className="btn" onClick={csv}><Download size={15}/> CSV</button><button className="btn btn-primary" onClick={()=>window.print()}><Printer size={15}/> Print / PDF</button></div></div>
 {msg&&<div className="command no-print"><div><b>{msg}</b></div><i className="pulse"/></div>}<section className="panel no-print" style={{marginTop:18}}><div className="form-grid"><div className="field"><label>DEPARTMENT</label><select value={dept} onChange={e=>setDept(e.target.value)}>{departments.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>PRIMARY METRIC</label><select value={metric} onChange={e=>setMetric(e.target.value)}><option value="performance">Performance</option><option value="workload">Workload</option><option value="completeness">Completeness</option></select></div><div className="field"><label>LOAD PRESET</label><select defaultValue="" onChange={e=>{const p=presets.find((x:any)=>String(x.id)===e.target.value);if(p){setDept(p.configuration?.department||'All');setMetric(p.configuration?.metric||'performance')}}}><option value="">Choose saved preset</option>{presets.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>PRESET NAME</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Monthly staff development"/></div><button className="btn" onClick={save}><Save size={15}/> Save preset</button></div></section>
 <section className="panel report-print" style={{marginTop:18}}><div className="panel-head"><div><small>TEACHTRACK MANAGEMENT REPORT</small><h2>{dept} · {metric}</h2><p>Generated {new Date().toLocaleDateString('en-GB',{timeZone:'Asia/Colombo'})}</p></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Teacher</th><th>Department</th><th>Performance</th><th>Workload</th><th>Completeness</th><th>Trend</th></tr></thead><tbody>{rows.sort((a:any,b:any)=>(b as any)[metric]-(a as any)[metric]).map((x:any)=><tr key={x.teacher.id}><td>{x.teacher.name}</td><td>{x.teacher.department}</td><td>{x.performance}%</td><td>{x.workload}</td><td>{x.completeness}%</td><td>{x.trend}</td></tr>)}</tbody></table></div><div className="report-signature"><span>Prepared by: ____________________</span><span>Principal: ____________________</span></div></section></>
}