'use client'
import { FormEvent,useState } from 'react'
import { useData } from '@/components/DataProvider'
export default function GoalCheckins(){
 const{data,loading,profile,role,insert,update}=useData();const[msg,setMsg]=useState('');const leadership=['principal','vice_principal','section_head','reviewer'].includes(role)
 const goals=(data.goals||[]).filter((g:any)=>leadership||String(g.teacher_id)===String(profile?.teacher_id))
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),goal=goals.find((g:any)=>String(g.id)===String(fd.get('goal_id')));if(!goal)return;try{const progress=Number(fd.get('progress')||0);await insert('goal_checkins',{goal_id:Number(goal.id),teacher_id:Number(goal.teacher_id),progress,note:String(fd.get('note')||''),evidence_url:String(fd.get('evidence_url')||'')||null,checkin_date:String(fd.get('checkin_date'))});await update('goals',goal.id,{current_value:progress,status:progress>=Number(goal.target_value||100)?'Completed':goal.status==='At Risk'?'At Risk':'Active'});setMsg('Goal check-in saved and goal progress updated.')}catch(err:any){setMsg(err.message)}}
 if(loading)return <div className="loading">Loading goal check-ins…</div>
 const rows=[...(data.goal_checkins||[])].filter((x:any)=>goals.some((g:any)=>String(g.id)===String(x.goal_id))).sort((a:any,b:any)=>String(b.checkin_date).localeCompare(String(a.checkin_date)))
 return <><div className="page-head"><div><span className="eyebrow"><i className="dot"/>Development check-ins</span><h1 style={{marginTop:14}}>Goal progress updates</h1><p>Add small evidence-based progress updates instead of waiting until a goal is complete.</p></div></div>{msg&&<div className="command"><div><b>{msg}</b></div><i className="pulse"/></div>}
 <div className="grid-2" style={{marginTop:18}}><section className="panel"><h3>Add check-in</h3><form className="form-grid" onSubmit={submit}><div className="field full"><label>GOAL</label><select name="goal_id" required>{goals.map((g:any)=><option key={g.id} value={g.id}>{g.title}</option>)}</select></div><div className="field"><label>PROGRESS %</label><input name="progress" type="number" min="0" max="100" required/></div><div className="field"><label>DATE</label><input name="checkin_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field full"><label>UPDATE</label><textarea name="note" required/></div><div className="field full"><label>EVIDENCE URL (OPTIONAL)</label><input name="evidence_url"/></div><button className="btn btn-primary full">Save check-in</button></form></section><section className="panel"><h3>Recent check-ins</h3>{rows.slice(0,30).map((x:any)=><div className="queue-row" key={x.id}><div><b>{goals.find((g:any)=>String(g.id)===String(x.goal_id))?.title||'Goal'}</b><small>{x.checkin_date} · {x.note}</small></div><span>{x.progress}%</span></div>)}{!rows.length&&<div className="empty">No check-ins yet.</div>}</section></div></>
}